### ISSUE TITLE
Label text seems misaligned

### ISSUE THREAD

**Issue by mrcprgt** [BilalShahid13/PersistentBottomNavBar#1]
Is it supposed to be that way? The label text on styles 1 and 7 seems to be misaligned.

**Comment by BilalShahid13** [comment]
No it's not. I'll fix it and push an update ASAP!

**Comment by mrcprgt** [comment]
Okay. Thanks for the good work!

**Comment by BilalShahid13** [comment]
It's fixed. Please check version `1.2.1`. Also, the GIFs on the Readme are still not updated. I will update them when I have the time.

Thanks for pointing it out.
