### ISSUE TITLE
Use RouteObserver with PersistentBottomNavBar 

### ISSUE THREAD

**Issue by Yetispapa** [BilalShahid13/PersistentBottomNavBar#101]
we're using your great plugin for implementing a consistent tabbar in our app. Now we notice that  [RouteObserver](https://api.flutter.dev/flutter/widgets/RouteObserver-class.html), which we really rely on, is not working anymore. The problem, as it seems, comes from the different navigators which are created for each tab in the PersistentBottomNavBar. From a quick dive into your code, I actually found a parameter from the used CustomTabView-Widget. So maybe its not a big deal for you.

```
class CustomTabView extends StatefulWidget {
  const CustomTabView({
    Key key,
    this.builder,
    this.navigatorKey,
    this.defaultTitle,
    this.routes,
    this.onGenerateRoute,
    this.onUnknownRoute,
    this.routeName,
    **this.navigatorObservers = const <NavigatorObserver>[],**
....
```

Is it possible for you to implement a solution where we can use the RouteObserver?

So like we do for our MaterialApp:

```
MaterialApp(
    home: Container(),
    navigatorObservers: [routeObserver],
  )
```

There should be a parameter like:

```
PersistentTabView(
    navigatorObservers: [routeObserver],
..
```

Thank you in advance

**Comment by BilalShahid13** [comment]
That's an interesting problem. I'll see what I can do and inform you soon about it.

**Comment by Yetispapa** [comment]
Hey @BilalShahid13. Its actually super critical for us. So thanks for you help!

**Comment by BilalShahid13** [comment]
I sincerely apologise but I'm just too busy these days to work on this package. Hopefully I can do something in the upcoming weekend.

**Comment by Yetispapa** [comment]
Hi @BilalShahid13. We wanted to ask if you find time to dig into the ticket. Thanks again!

**Comment by Yetispapa** [comment]
Hey @BilalShahid13. I wanted to ask, if you have any updates on our ticket?

**Comment by BilalShahid13** [comment]
Argument `navigatorObservers` added in the latest build _3.0.0_. Apologies for the delay.

**Comment by BilalShahid13** [comment]
There have been updates in the latest version of the package which further improves the navigator and route settings. Thank you.
