### ISSUE TITLE
Crashing on iOS 14.2

### ISSUE THREAD

**Issue by kirkcharlesniv** [BilalShahid13/PersistentBottomNavBar#109]
Tested on iPhone 8 Plus, iPhone 11 Pro with iOS 14.2 version. (Simulator Version 12.1.1 (940.16))

Results on `Lost connection to device.` when the screen with Persistent Bottom NavBar shows.

Tested on latest Android, no problem.

**Comment by BilalShahid13** [comment]
I didn't face any issue. Can you test the latest _3.0.0_ version?

**Comment by kirkcharlesniv** [comment]
Sorry for the late reply, I guess upgrading to 3.0.0 fixes it. Thanks!
