### ISSUE TITLE
How to jump to a specific tab without tapping the BottomNavigationBar?

### ISSUE THREAD

**Issue by d-apps** [BilalShahid13/PersistentBottomNavBar#11]
I have a situation on my app that I am at some inner screen in the first tab and I needed programatically jump to the second tab.

When I use "**selectedIndex**" parameter from **PersistentTabView()**, setting a new int according to the screen I need to jump to, it doesn't work. I tried using the PersistentTabController too, but it doesn't have a .jumpToPage function. Is there ay workaround to achieve this?

I am using MobX as state management.

```
PersistentTabController _persistentTabViewController = PersistentTabController(initialIndex: 0);

Observer(
        builder: (_) {
          return PersistentTabView(
            controller: _persistentTabViewController,
            items: bottomTitles.asMap().map((index, title){

              return MapEntry(index, PersistentBottomNavBarItem(
                icon: Icon(bottomIcons[index]),
                title: (bottomTitles[index]),
                activeColor: Theme.of(context).primaryColor,
                inactiveColor: Colors.grey,
                isTranslucent: false,
                )
              );

            }).values.toList(),
            screens: tabs,
            showElevation: false,
            navBarCurve: NavBarCurve.none,
            iconSize: 20,
            navBarStyle: NavBarStyle.style6,
            selectedIndex: MobXclass.tabSelectedIndex,
          );
        }
      ),
```

MobX class to call the action

```
  @observable
  int tabSelectedIndex = 0;

  @action
  void setTab(int n){
    tabSelectedIndex = n;
  }
```

**Comment by BilalShahid13** [comment]
You can do this by setting the index of the `PersistentTabView`. Don't forget to call `setState`.

`setState(() {
            _controller.index = 1;
  });`

I'll check why `selectedIndex` is not working. Thanks for reporting the bug.

**Comment by BilalShahid13** [comment]
I have removed `selectedIndex` property altogether as it was redundant. `PersistentTabController` is enough for this. Also I have added `jumpToTab` just in case someone doesn't realize about the other way. See version `1.5.1`.

This issue is now being closed.

**Comment by nguyenkhoi2806** [comment]
> I have removed `selectedIndex` property altogether as it was redundant. `PersistentTabController` is enough for this. Also I have added `jumpToTab` just in case someone doesn't realize about the other way. See version `1.5.1`.
> 
> This issue is now being closed.
can you tell detail how to use it, when i call " _controller.jumpToTab(1); " and i get this error " The method 'jumpToTab' was called on null" 
thanks

**Comment by d-apps** [comment]
> > I have removed `selectedIndex` property altogether as it was redundant. `PersistentTabController` is enough for this. Also I have added `jumpToTab` just in case someone doesn't realize about the other way. See version `1.5.1`.
> > This issue is now being closed.
> > can you tell detail how to use it, when i call " _controller.jumpToTab(1); " and i get this error " The method 'jumpToTab' was called on null"
> > thanks

Probably you're not initializing your controller before calling jumpToTab().
PersistentTabController controller = PersistentTabController;

I initialize on initState normally.

PersistentTabController controller;

initState(){
controller = PersistentTabController;
}

**Comment by nguyenkhoi2806** [comment]
> Probably you're not initializing your controller before calling jumpToTab().
> 
> PersistentTabController controller = PersistentTabController;
> 
> I initialize on initState normally.
> 
> PersistentTabController controller;
> 
> initState(){
> controller = PersistentTabController;
> }

Thank your reply, The error doesnot show anymore but the screen didn't change !!! What i miss here
