### ISSUE TITLE
NavBarStyle.style1 error

### ISSUE THREAD

**Issue by vuthasothea** [BilalShahid13/PersistentBottomNavBar#115]
`Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<Flexible>(Closure: (PersistentBottomNavBarItem) => Flexible))`

**Comment by tomboffos222** [comment]
this problem too and i don't know how to fix

**Comment by BilalShahid13** [comment]
Thank you for reporting it. I'll release a fix soon.

**Comment by BechirAhmed** [comment]
Any new update??

**Comment by joanofdart** [comment]
Soon... 18 days and counting :P

**Comment by EngALAlfy** [comment]
i know how to fix it it is error in the package code
in this file    [ C:/Users/USER_NAME/.flutter_sdk/.pub-cache/hosted/pub.dartlang.org/persistent_bottom_nav_bar-3.1.0/lib/models/persistent-bottom-nav-bar.widget ]  

in line 205

`case NavBarStyle.style1:
          return BottomNavStyle1();`

change to 

`case NavBarStyle.style1:
          return BottomNavStyle1(
            navBarEssentials: this.navBarEssentials,
          );`

**Comment by JaffaKetchup** [comment]
Any news on this?

**Comment by BilalShahid13** [comment]
Should be fixed in the latest version. Thank you for your patience.
