### ISSUE TITLE
hideNavigationBarWhenKeyboardShows

### ISSUE THREAD

**Issue by furrknyilmazz** [BilalShahid13/PersistentBottomNavBar#116]
hideNavigationBarWhenKeyboardShows not working

**Comment by BilalShahid13** [comment]
What version are you using?

**Comment by Sheetal-25** [comment]
having the same issue **persistent_bottom_nav_bar: 2.1.0**

**Comment by furrknyilmazz** [comment]
I use 3.1.0

**Comment by Joyker** [comment]
3.1.0, custom widget, not working

**Comment by ShabbirK52** [comment]
In version 3.1.0, the bottom nav bar automatically hides when the keyboard is being used.

**Comment by ehaberkorn** [comment]
Same here. Using the 3.1.0 version with PersistentTabView.custom the bar is still visibile if the keyboard is shown.

**Comment by BilalShahid13** [comment]
This should be fixed in the latest version. Working for me in the example project. Thank you.

**Comment by sumitbhanushali** [comment]
not working for me too, i am on version persistent_bottom_nav_bar: ^4.0.2

**Comment by Irfadg** [comment]
> 

hey..did you find the solution??
