### ISSUE TITLE
how to change tab item runtime

### ISSUE THREAD

**Issue by anup-geeky** [BilalShahid13/PersistentBottomNavBar#122]
For guest user my app tab items are 3, when user sing up then I want to show 4 tab item.....so how I can update tab item runtime without reopening the app.

**Comment by BilalShahid13** [comment]
The tabs are defined in an array of type `PersistentNavBarItem`. You just have to add or remove the last tab from that array. Make sure you remove the corresponding screen from the screens array as well else it will throw an exception.
