### ISSUE TITLE
PersistentTabView Scaffold Color

### ISSUE THREAD

**Issue by on3ss** [BilalShahid13/PersistentBottomNavBar#125]
Is there no way to change the backgound color of the scaffold that is wrapping the PersistentTabView? It seems currently it is hardcoded to transparent but I want to change it to black. Is this possible?

**Comment by BilalShahid13** [comment]
You can wrap the PersistentTabView in a Scaffold and set its color to black.

**Comment by fraca98** [comment]
Good morning, i'm sorry, i'm facing some issues trying to do this, can i see your solution?
