### ISSUE TITLE
Screen resize causing rebuild

### ISSUE THREAD

**Issue by redhajuanda** [BilalShahid13/PersistentBottomNavBar#128]
Hi, I have an issue with this package, whenever the screen resize in the child widget (like opening or closing keyboard, screen orientation changes), it causes rebuild all screens that defined in screens property (main screen), do you have any idea how to fix this, thanks

**Comment by redhajuanda** [comment]
Note: the example app produces the same issue, I think this is undesired because if we use FutureBuilder in the main screen, it will lead to re-fetching api over and over again.

**Comment by vetermol4it** [comment]
Remove property "resizeToAvoidBottomInset". It's working for me

**Comment by BilalShahid13** [comment]
I think you can go with the fix @vetermol4it mentioned.
