### ISSUE TITLE
Only use navBarStyle: NavBarStyle.custom , don't use another style

### ISSUE THREAD

**Issue by khaitq7** [BilalShahid13/PersistentBottomNavBar#13]
Dear there ,
Thank for your library , It's very perfect . But I use a litte problem .
I don't use another style for bottom navigation .

> 
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#201f7):
'package:persistent_bottom_nav_bar/persistent-tab-view.widget.dart': Failed assertion: line 38 pos 12: 'navBarStyle == NavBarStyle.custom && customWidget != null ||
        navBarStyle != NavBarStyle.custom && customWidget == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MyHomePage file:///F:/CodeExample/Flutter/custom_bottom_navigation/lib/main.dart:21:13
When the exception was thrown, this was the stack: 
#2      new PersistentTabView (package:persistent_bottom_nav_bar/persistent-tab-view.widget.dart:38:12)
#3      _MyHomePageState.build (package:custombottomnavigation/main.dart:84:12)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
...

**Comment by BilalShahid13** [comment]
Because you are declaring custom *widget* along but not using the custom *style*.

Declare your main widget like this:


```dart
 @override
  Widget build(BuildContext context) {
    return PersistentTabView(
      controller: _controller,
      items: _navBarsItems(),
      screens: _buildScreens(),
      showElevation: true,
      navBarCurve: NavBarCurve.upperCorners,
      confineInSafeArea: true,
      handleAndroidBackButtonPress: true,
      iconSize: 26.0,
      navBarStyle: NavBarStyle.style1, // Choose the nav bar style with this property
      onItemSelected: (index) {
        print(index);
      },
    );
  }
```

**Comment by khaitq7** [comment]
Thank you so much
