### ISSUE TITLE
NavBarStyle.Style1 and Style11 dont work

### ISSUE THREAD

**Issue by quantass** [BilalShahid13/PersistentBottomNavBar#135]
Setting navbarStyle to style1 or style11 throws a null error.  I had to update persistent-bottom-nav-bar.widget.dart method "getNavBarStyle" to include **navBarEssentials: this.navBarEssentials** in  the constructor for BottomNavStyle1 and BottomNavStyle11.

**Comment by BilalShahid13** [comment]
Thanks JaffaKetchup for your PR. Issue should be fixed in the latest release now. Thank you.
