### ISSUE TITLE
routeAndNavigatorSettings being copied for each Tab

### ISSUE THREAD

**Issue by quantass** [BilalShahid13/PersistentBottomNavBar#136]
It seems odd that setting routeAndNavigatorSettings within the PersistentTabView would then **clone** that information to each tab.  It would seem more sensible to have routeAndNavigatorSettings  parameter for each PersistentBottomNavBarItem then on creation of each tab to then pull this tab specific routeAndNavigatorSettings  setting for that tab's navigator.

**Comment by BilalShahid13** [comment]
Thank you for your suggestion. It is implemented just like that in the latest version.
