### ISSUE TITLE
Plans on supporting null safety?

### ISSUE THREAD

**Issue by DanMossa** [BilalShahid13/PersistentBottomNavBar#137]
Hello!

I was wondering if there were any plans to support null safety?

Thanks!

**Comment by rc8marcelo** [comment]
Flutter 2.0 just released and null safety has been made stable. Is there any update if the package will be supporting null safety?

**Comment by pacholoamit** [comment]
Hello yeah I'm also interested to inquire if this would support null safety.

**Comment by DanMossa** [comment]
I'll make a PR to support null-safety later today!

**Comment by KgotsoK** [comment]
Thank you @DanMossa!!

**Comment by DanMossa** [comment]
Quick PR in #144 
I'm using my repo/branch in the meantime like this in pubspec.yaml
```
  persistent_bottom_nav_bar:
    git: git@github.com:DanMossa/PersistentBottomNavBar.git
```

Until this gets merged into the official repo.

**Comment by RealBug** [comment]
> Quick PR in #144
> I'm using my repo/branch in the meantime like this in pubspec.yaml
> 
> ```
>   persistent_bottom_nav_bar:
>     git: git@github.com:DanMossa/PersistentBottomNavBar.git
> ```
> 
> Until this gets merged into the official repo.

Thanks for the work, it's cool! However, I don't think it's a good idea this merge request because it's more than "Quick and dirty", it could generate crashes with the "!".

**Comment by DanMossa** [comment]
@RealBug 
Yeah, that's a fair point. I have been using it on my production app with no issues though.
 I actually think this repo may not be managed at this point seeing as how there's an open PR from November

**Comment by KgotsoK** [comment]
Yeah. I have been checking here often to see if @BilalShahid13 would comment.

**Comment by KgotsoK** [comment]
Currently using @DanMossa's version. I really hope we can get this sorted

```
  persistent_bottom_nav_bar:
    git: git@github.com:DanMossa/PersistentBottomNavBar.git
```

**Comment by BilalShahid13** [comment]
I'm sorry to keep you all waiting. I have been really busy with my office work and in pandemic conditions it was next to impossible to find some spare time. I have committed to deliver updates before but failed to do so unfortunately. But I am glad to tell you all that most of the nuisances have been resolved and I will be working at full steam moving forward hopefully. You can anticipate a big release in the coming days :) Thank you for your patience.

**Comment by BilalShahid13** [comment]
Null safety is now supported! Please check the latest build.
