### ISSUE TITLE
Getting black screen after closing the alert dialog

### ISSUE THREAD

**Issue by TheDeveloperYJ** [BilalShahid13/PersistentBottomNavBar#14]
Hey, I am facing an issue. I have a list of items displaying on the page and when I select an item it goes to a new screen with details of that item. I have a delete button on the appBar. When the user presses the button it confirms whether user wants to delete it using Alert dialog. But when I press delete it goes back to a black screen. I know I am missing something here. Let me know what it is
Here is the code:

 showDialog(
                    context: context, // user must tap button!
                    builder: (BuildContext context) {
                      return AlertDialog(
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(8.0)),
                        title: Text('Are you sure you want to delete'),
                        actions: <Widget>[
                          FlatButton(
                            child: Text('CANCEL'),
                            onPressed: () {
                              Navigator.of(context).pop();
                            },
                          ),
                          FlatButton(
                            child: Text('DELETE'),
                            onPressed: () {
                  
                              _deletefromDb(data['id'], context);
                              // Navigator.of(context).pop();
                              
                                Navigator.pop(context);
                              //  Navigator.pushReplacementNamed(context, 'saved');
                              // Navigator.of(context).popUntil((route) {
                              //   return route.settings.name ==
                              //       "Saved";
                              // });
                            },
                          ),
                        ],
                      );
                    },
                  );

 _deletefromDb(int id, context) async {
    var result = await databaseHelper.deleteLyrics(id);
    SavedBlocProvider.of(context).getSavedList();
    if (result != 0) {
      // Navigator.of(context).pop();
     
    }
  }

**Comment by BilalShahid13** [comment]
I tested your code and for me, it is working as intended. 

The problem that you described occurs when the context is not being passed down correctly. So when you will call `Navigator.pop(context)`, it will pop the previous screen as it is receiving the **context** of that screen instead of the dialog. Try renaming the name of the dialog's **context variable** to something like `dialogContext` and then use it like this `Navigator.pop(dialogContext)`.

**Comment by TheDeveloperYJ** [comment]
Yes this solves the issue ! Thank you and I really like this package
