### ISSUE TITLE
Is there any way using which we can hide navbar on particular screen?

### ISSUE THREAD

**Issue by DhavalRKansara** [BilalShahid13/PersistentBottomNavBar#140]
Is there any way using which we can hide navbar on particular screen?

**Comment by DhavalRKansara** [comment]
Fixed it by pushing the screen using `pushNewScreen`.

```
pushNewScreen(context, screen: ScanQrScreen(), withNavBar: false)
```

**Comment by aliazimoshan** [comment]
> Fixed it by pushing the screen using `pushNewScreen`.
> 
> ```
> pushNewScreen(context, screen: ScanQrScreen(), withNavBar: false)
> ```

Thank it solved my problem

**Comment by zeyneptoy** [comment]
It is working, perfect. Thank you!
