### ISSUE TITLE
Cannot set asset image to icon  PersistantBottomNavBarItem

### ISSUE THREAD

**Issue by balaji101010** [BilalShahid13/PersistentBottomNavBar#142]
If I use ImageIcon to `PersistantBottomNavBarItem` to icon field, 
The image looks shrinked!
```

`   PersistentBottomNavBarItem(
          icon: ImageIcon(
            AssetImage("image.png"),
            size: 24,
          ),
          activeColor: AppColors.primaryColor,
          inactiveColor: AppColors.onBackgroundColor2,
          title: AppLocalizations.of(context).toExplore),`
```

**Comment by BilalShahid13** [comment]
Thank you for the feedback. This problem will be covered in issue #138.

**Comment by pupubird** [comment]
For those who still stumbled across this issue, just convert your image to icon: https://medium.com/deviniti-technology-driven-blog/the-best-way-to-add-custom-icons-to-your-flutter-project-6381ab697813
