### ISSUE TITLE
Pop to root screen (login screen) without bottom nav bar

### ISSUE THREAD

**Issue by sravanpabolu** [BilalShahid13/PersistentBottomNavBar#146]
Hi,

my app structure is as follows

IntroScreens > Login Screen > Dashboard screen (PersistentBottomNavBar)

I use `pushNewScreen` in login screen to navigate to Dashboard screen, which works fine. 

During logout, I use `Navigator.of(context).popAndPushNamed(LoginScreen.routeName);` If I use this, I am able to navigate to login screen, but bottom navigation bar is not pop'ed / disposed. It's still alive and I could interact with it. 

How do I completely remove bottom nav bar ? 

The package version I am using is v3.1.0

**Comment by Rohithgilla12** [comment]
+1

**Comment by Rohithgilla12** [comment]
https://github.com/BilalShahid13/PersistentBottomNavBar/issues/70

**Comment by BilalShahid13** [comment]
This scenario as mentioned by @Rohithgilla12, has been discussed already. Please refer to the said issue #70.
