### ISSUE TITLE
Disable PageTransitionAnimation 

### ISSUE THREAD

**Issue by fettespferd** [BilalShahid13/PersistentBottomNavBar#147]
Instead of having a fancy Transition I just want that the new screen appears instantly. That is currently not possible right?

**Comment by BilalShahid13** [comment]
It is possible. Set the property `screenTransitionAnimation` in main _PersistentTabView_ widget like this:

```dart
      screenTransitionAnimation: ScreenTransitionAnimation(
          animateTabTransition: false,
          curve: Curves.ease,
          duration: Duration(milliseconds: 200),
      ),
```

**Comment by fettespferd** [comment]
Thanks for the answer 👍🏽
