### ISSUE TITLE
Screen stacked

### ISSUE THREAD

**Issue by faizbinyousuf** [BilalShahid13/PersistentBottomNavBar#149]
Hi, 
I am using this nav bar for the first time. Whenever I try to logout from app, the user is redirected to the login page, where the bottom bar is not required. But the login screen is being pushed on top of the current tab. Also, when logged in again, I
am getting two nav bars, one on top of another.  How to navigate to a page that does not require a bottom bar?

Screenshots attached
link 1:https://user-images.githubusercontent.com/44543054/111439843-c433ba80-872b-11eb-9543-95fb743a5342.jpg
link 2 : https://user-images.githubusercontent.com/44543054/111440186-1e348000-872c-11eb-81a1-4b03462e43b9.jpg

**Comment by BilalShahid13** [comment]
You are probably not popping the screen where the navigation bar is declared. See #70. Thank you.

**Comment by faizbinyousuf** [comment]
thank you.
