### ISSUE TITLE
Get black background color behind border radius

### ISSUE THREAD

**Issue by Mint-io** [BilalShahid13/PersistentBottomNavBar#15]
There may be two reasons to cause this problem (screenshot below):
1) Increase both upper border radius
2) decrease nav bar height a low
What I thought is to change the property to cause black background to Colors.transparent. But unfortunately I cannot handle it by myself.

Also, it will be great to add a property for adjusting both upper border radius in PersistentTabView() method if (customWidget == null)

Thanks in advance!

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-07 at 19 44 26](https://user-images.githubusercontent.com/52114394/81357427-9f010500-90a1-11ea-8c35-36c9418d6079.png)

**Comment by BilalShahid13** [comment]
I'll fix this and push an update as soon as possible! Also, I might hopefully add the features that you suggested.

Thanks for reporting the bug.

**Comment by BilalShahid13** [comment]
Can now be changed in the latest version.

```dart
decoration: NavBarDecoration(
        colorBehindNavBar: Colors.white,
      ),
```
