### ISSUE TITLE
The following _CastError was thrown building CustomTabView

### ISSUE THREAD

**Issue by saeedtaha96** [BilalShahid13/PersistentBottomNavBar#153]
The following _CastError was thrown building CustomTabView(dirty, state: _CustomTabViewState#04cfb):
type 'List<NavigatorObserver?>' is not a subtype of type 'List<NavigatorObserver>' in type cast

The relevant error-causing widget was: 
  CustomTabView file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/persistent_bottom_nav_bar-4.0.0/lib/persistent-tab-view.widget.dart:551:14
When the exception was thrown, this was the stack: 
#0      _CustomTabViewState.build (package:persistent_bottom_nav_bar/models/tab-view.widget.dart:52:38)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)

**Comment by BilalShahid13** [comment]
See #154. Thanks.
