### ISSUE TITLE
v1.5+ issue - tabbing on first tab bar item pops the whole stack 

### ISSUE THREAD

**Issue by SogoGolf** [BilalShahid13/PersistentBottomNavBar#16]
for versions 1.5+ there is an issue with tapping on tab bar items.

issue is:
1. on first tab, tap into a stack -> one or two deep
2. tap on second tab
3. tap ONCE on first tab - it automatically pops/resets the entire stack on the first tab!

ideally this behavior should be defined via a property on the ```PersistentTabView```. something like `resetStackOnNavBarItemTap` (true/false). that way we can decide how we want the app to behave if user does this.

at the moment (v1.5) what its doing on iOS is noted above.

**Comment by BilalShahid13** [comment]
Yes, I added it as a feature quite recently. As it is a part of the default behavior of iOS bottom navigation bar, I felt no need to give an option. But I think you have valid argument and I will add an option to disable it soon.

**Comment by SogoGolf** [comment]
Ok perfect thanks

**Comment by BilalShahid13** [comment]
Please check the latest version. I have added a property `popAllScreensOnTapOfSelectedTab` which is set to true by default. Set it to **false** to disable this behavior.

**Comment by SogoGolf** [comment]
works perfectly @BilalShahid13 , many thanks
