### ISSUE TITLE
How to set up routes? 

### ISSUE THREAD

**Issue by talmr-k** [BilalShahid13/PersistentBottomNavBar#162]
In MaterialApp, I'm defining a `home: Gatekeeper()`.  Based on whether or not there is an authenticated user, this widget will show either the main app (where I use the PersistentTabView), or the Login screen.

Anyway, I have push notifications that on tap will route the user to some place in my app.  For instance, there's a cool event near you so you receive a notification for it, internally the app wants to navigate to `/events/details` route.

Where should I define these named routes?  I am confused after reading through various issues here, and looking at the code.  I've currently defined my routes in MaterialApp's `onGenerateRoute`, but I can't get this to work with PersistentTabView.

**Comment by amoo12** [comment]
hi, did you find a solution?
I am facing the same problem
