### ISSUE TITLE
How to hide the Bottom Nav Bar Dynamically 

### ISSUE THREAD

**Issue by Maadhav** [BilalShahid13/PersistentBottomNavBar#17]
I am currently building an app where I need to keep an option of fullscreen. The problem is that I also need to hide the bottom navigation bar dynamically. Is there any way to do this within this plugin.

**Comment by nguyenkhoi2806** [comment]
pushNewScreen(
        context,
        screen: HomeScreen(),
        withNavBar: false, // OPTIONAL VALUE. True by default.
    );

**Comment by Maadhav** [comment]
No, this isn't what I want, I want to hide and show the bottom nav for the same screen, not after navigating. I have a boolean of isFullScreen. So when it is true, hide the nav bar else display the navbar.

**Comment by BilalShahid13** [comment]
Set `navBarHeight` to **0**

**Comment by Maadhav** [comment]
Thanks! But I anyway used the normal bottom navbar with provider to give
more efficient results.

**Comment by BilalShahid13** [comment]
With the purpose of this question fulfilled, I'm closing this thread.
