### ISSUE TITLE
White background shows when keyboard appears

### ISSUE THREAD

**Issue by sinangokce** [BilalShahid13/PersistentBottomNavBar#173]
Hello,

Great work with this package! I'm using ic for my current project however I'm facing an issue with keyboard appearing. Specifically, a white background comes to screen for a short time when the keyboard pops up. This is then giving an impression that the app is buggy. I've already set the parameters "resizeToAvoidBottomInset" and "hideNavigationBarWhenKeyboardShows" to both true and false. 

If I don't wrap my child widgets inside "PersistentTabView" widget, I don't have this white background behind the keyboard. This is because text fields are wrapped up inside a Scaffold widget with resizeToAvoidBottomInset: false, backgroundColor: Colors.transparent. 

Can you help me with that?

Thanks!

**Comment by sinangokce** [comment]
I'm using latest version: **persistent_bottom_nav_bar: ^4.0.2**

**Comment by SilkeNL** [comment]
If you have a Scaffold you can use `resizeToAvoidBottomInset: true`
From a StackOverFlow question: https://stackoverflow.com/questions/58685174/flutter-how-to-remove-the-white-background-behind-the-keyboard-when-keyboard-go

From the docs: https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html

**Comment by SilkeNL** [comment]
Can you show some code?

**Comment by sinangokce** [comment]
I found out that I missed there was one hidden scaffold widget wrapping another one. Thanks!
