### ISSUE TITLE
popAllScreensOnTapOfSelectedTab is not working

### ISSUE THREAD

**Issue by anup-geeky** [BilalShahid13/PersistentBottomNavBar#18]
popAllScreensOnTapOfSelectedTab is not working.

**Comment by BilalShahid13** [comment]
Yes it does not work in some cases. The reason is that I'm using the **Navigator.canPop(context)** to determine whether the screen can be popped or not and sometimes it doesn't work properly. I don't know why it does that yet but I'm looking to find the fix.

**Comment by BilalShahid13** [comment]
Fixed in latest version!
