### ISSUE TITLE
Add drawer/endDrawer option.

### ISSUE THREAD

**Issue by anup-geeky** [BilalShahid13/PersistentBottomNavBar#19]
@BilalShahid13 
In my project I want to end drawer and show accross all screen for that I have used Scafflod and set PersistentTabView to body. But problem is bottom navigation bar show above keyboard when I click on textfield. If I set value to resizeToAvoidBottomInset=true textfield get hide below keyboard. 

So can provide any solution to this.

Thank you.

**Comment by BilalShahid13** [comment]
You cannot hide the tab bar as it is part of the screen. Wrap the `PersistentTabView` in a *Scaffold* with `resizeToAvoidBottomInset` set to *true* then wrap your screen in `SingleChildScrollView`. You will then be able to scroll to the text field on your screen.

**Comment by BilalShahid13** [comment]
Navigation Bar can now be hidden in the latest version. Please see the latest readme. Also it includes the property `resizeToAvoidBottomInset` and `hideNavigationBarWhenKeyboardShows`.

**Comment by jicasa03** [comment]
you can send me your example with drawer
