### ISSUE TITLE
How to handle android back button

### ISSUE THREAD

**Issue by elango** [BilalShahid13/PersistentBottomNavBar#2]
Hi,

Can you please provide your input on how can we handle the hardware back button when the view is pushed. 

Right now when tapping the hardware back button closes the app.

Thanks.

**Comment by jefferyleo** [comment]
Yes, this is the question I wanted to ask too. I don't think this support the android back button navigation yet, anyhow see how does @BilalShahid13 reply on this.

**Comment by BilalShahid13** [comment]
Hi,

There is no perfect solution at the moment as android doesn't allow us to override the back button. There is a work around though and you can use the flutter package `back_button_interceptor` to solve your problem. It works most of the time but not all the time. The best solution would be to enable the `platformSpecific` property.

This is the reason I had to add the `platformSpecific` option because persistent bottom navigation is not consistent with the Android design guidelines.

**Comment by BilalShahid13** [comment]
> Hi,
> 
> Can you please provide your input on how can we handle the hardware back button when the view is pushed.
> 
> Right now when tapping the hardware back button closes the app.
> 
> Thanks.

If you want to just prevent the unintended closure of the app, I would suggest using `onWillPop` 

Offical Documentation: https://api.flutter.dev/flutter/widgets/WillPopScope-class.html

Wrap your widget inside `WillPopScope` and return a false Future in the `onWillPop` property

Example: 

```
@override
Widget build(BuildContext context) {
  return WillPopScope(
    child: Scaffold(...),
    onWillPop: () => showDialog<bool>(
      context: context,
      builder: (c) => AlertDialog(
        title: Text('Warning'),
        content: Text('Do you really want to exit'),
        actions: [
          FlatButton(
            child: Text('Yes'),
            onPressed: () => Navigator.pop(c, true),
          ),
          FlatButton(
            child: Text('No'),
            onPressed: () => Navigator.pop(c, false),
          ),
        ],
      ),
    ),
  );
}

```

**Comment by BilalShahid13** [comment]
I think I should mention it in the Readme as this is a genuine issue with only a work around available at the moment. 

Thank you for pointing out

**Comment by BilalShahid13** [comment]
The issue where the app closes if android's back button is pressed is fixed in latest version `1.3.0`.

**Comment by SogoGolf** [comment]
great component thanks! any eta on a back button fix for Android ?

**Comment by thivankasarathchandra** [comment]
Now app is not exiting at all

**Comment by BilalShahid13** [comment]
> great component thanks! any eta on a back button fix for Android ?

I have fixed it 🎉 New version will be hopefully up tomorrow after l update the sample project and the readme. Stay tuned!

**Comment by BilalShahid13** [comment]
> Now app is not exiting at all

Noted! Stay tuned for the next version with the fix which I will release tomorrow.

**Comment by BilalShahid13** [comment]
New version `1.4.1` is up. The Android hardware/software back button is now being correctly handled. Check the updated sample project and readme.

I'm closing this issue for now 🎉

**Comment by fernando-s97** [comment]
What about changing the first scenario from
///1. If the you are on the first tab with all screens popped of the given tab, the app will close.
to
///1. If the you are on the first tab with all screens popped of the given tab, the app request to press the back button again (or any other way to prevent suddenly leaving the app).

How can I achieve this?

**Comment by BilalShahid13** [comment]
It's not possible at the moment but I'll release an update soon with this feature. Stay tuned!

**Comment by fernando-s97** [comment]
Hi!

If I do this, onWillPop isn't executed. Is there a way to make this work?

```dart
@override
Widget build(BuildContext context) {
  return WillPopScope(
    child: Scaffold(...),
    onWillPop: () => showDialog<bool>(
      context: context,
      builder: (c) => AlertDialog(
        title: Text('Warning'),
        content: Text('Do you really want to exit'),
        actions: [
          FlatButton(
            child: Text('Yes'),
            onPressed: () => Navigator.pop(c, true),
          ),
          FlatButton(
            child: Text('No'),
            onPressed: () => Navigator.pop(c, false),
          ),
        ],
      ),
    ),
  );
}
```

**Comment by BilalShahid13** [comment]
@fernando-s97 try to use the `onWillPop` property of `PersistentTabView` and see if that works for you. Also please note it will only work on android.
