### ISSUE TITLE
new feature - popping all "previous" screens from the navigation stack

### ISSUE THREAD

**Issue by SogoGolf** [BilalShahid13/PersistentBottomNavBar#20]
We have a requirement in our app whereby once a user gets to the 3rd screen in the navigation stack - we either:
(a) pop them all the way back to the first screen 
(b) take them to the 4th screen and then prevent them from going BACK (to screens 3/2/1). Then, once the tasks etc are completed on screens 4, 5 etc. => the user will be "popped" back to the 1st screen.

What would you suggest is best approach with PersistentBottomNavBar ?

**Comment by BilalShahid13** [comment]
**(a)** set `initialRoute` in your MaterialApp or CupertinoApp (depends on which you are using). Then just **Navigator.popUntil(context, ModalRoute.withName('nameOfTheInitalRoute'))**.

**(b)** To pop back to the first screen, use what I just suggested above. To prevent the user from popping using the *Scaffold*'s **AppBar**, override the AppBar's `leading` property. Then you can control yourself when to pop or not in the onPressed method of that let's say a FlatButton.

**Comment by SogoGolf** [comment]
ok cheers makes sense ill give that a try
