### ISSUE TITLE
how to add close dialog before closing app when using handlebackbutton

### ISSUE THREAD

**Issue by LoveAndroDev** [BilalShahid13/PersistentBottomNavBar#22]
Hi,

So i want to run a dialog before closing application when a handleAndroidBackButtonPress=true ?

**Comment by BilalShahid13** [comment]
It is not possible at the moment but it is a good feature request. I might add it soon and will let you know when I do.

Thank you.

**Comment by BilalShahid13** [comment]
Write your logic in `onWillPop` callback function. It will be called when you try to exit app on **Android only.**
