### ISSUE TITLE
How to return to the initial screen using the item in the navigation bar ?

### ISSUE THREAD

**Issue by felixferr** [BilalShahid13/PersistentBottomNavBar#24]
Hi,
Thx for this package, it's awesome !
I have a problem, i would like return to the initial screen when i press to the item in the navigation bar. How i do that ?
Thx for reply.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-27 at 22 35 29](https://user-images.githubusercontent.com/47897646/83069737-b57bfa00-a06a-11ea-8960-c3e466c5da25.png)

**Comment by BilalShahid13** [comment]
Have you set the property `popAllScreensOnTapOfSelectedTab` as true? If it still doesn't work then please wait. I'm working on a fix and will release an update soon. Stay tuned!

**Comment by felixferr** [comment]
still doesn't t work

**Comment by gapgag55** [comment]
> Have you set the property `popAllScreensOnTapOfSelectedTab` as true? If it still doesn't work then please wait. I'm working on a fix and will release an update soon. Stay tuned!

Still doesn't work too

**Comment by BilalShahid13** [comment]
Yes, it doesn't but I have fixed it already for sometime. The next update is quite comprehensive and took me a lot of time to complete. Some documentation changes only remain now and I will release as soon as I can. Thank you for your patience.

**Comment by BilalShahid13** [comment]
Fixed! Please update to latest version.

**Comment by felixferr** [comment]
Hi, i update to the latest version and this doesn't work. There is a method to do that ? Thx for reply

**Comment by BilalShahid13** [comment]
@felixferr can you share your code here?

**Comment by felixferr** [comment]
return PersistentTabView(
        controller: _controller,
        popAllScreensOnTapOfSelectedTab: true,
        screens: _buildScreens(),
        items:
            _navBarsItems(), // Redundant here but defined to demonstrate for other than custom style
        confineInSafeArea: true,
        backgroundColor: Colors.white,
        handleAndroidBackButtonPress: true,
        onItemSelected: (int) {
          setState(
              () {}); // This is required to update the nav bar if Android back button is pressed
        },
        customWidget: CustomNavBarWidget(
          items: _navBarsItems(),
          onItemSelected: (index) {
            setState(() {
              _controller.index = index;
              // THIS IS CRITICAL!! Don't miss it!
            });
          },
          selectedIndex: _controller.index,
        ),
        itemCount: 4,
        navBarStyle:
            NavBarStyle.custom // Choose the nav bar style with this property
        );

**Comment by felixferr** [comment]
` return PersistentTabView(
        controller: _controller,
        popAllScreensOnTapOfSelectedTab: true,
        screens: _buildScreens(),
        items:
            _navBarsItems(), // Redundant here but defined to demonstrate for other than custom style
        confineInSafeArea: true,
        backgroundColor: Colors.white,
        handleAndroidBackButtonPress: true,
        onItemSelected: (int) {
          setState(
              () {}); // This is required to update the nav bar if Android back button is pressed
        },
        customWidget: CustomNavBarWidget(
          items: _navBarsItems(),
          onItemSelected: (index) {
            setState(() {
              _controller.index = index;
              // THIS IS CRITICAL!! Don't miss it!
            });
          },
          selectedIndex: _controller.index,
        ),
        itemCount: 4,
        navBarStyle:
            NavBarStyle.custom // Choose the nav bar style with this property
        );`

**Comment by felixferr** [comment]
return PersistentTabView(
        controller: _controller,
        popAllScreensOnTapOfSelectedTab: true,
        screens: _buildScreens(),
        items:
            _navBarsItems(), // Redundant here but defined to demonstrate for other than custom style
        confineInSafeArea: true,
        backgroundColor: Colors.white,
        handleAndroidBackButtonPress: true,
        onItemSelected: (int) {
          setState(
              () {}); // This is required to update the nav bar if Android back button is pressed
        },
        customWidget: CustomNavBarWidget(
          items: _navBarsItems(),
          onItemSelected: (index) {
            setState(() {
              _controller.index = index;
              // THIS IS CRITICAL!! Don't miss it!
            });
          },
          selectedIndex: _controller.index,
        ),
        itemCount: 4,
        navBarStyle:
            NavBarStyle.custom // Choose the nav bar style with this property
        );

**Comment by BilalShahid13** [comment]
I see that you are using a custom widget. It's unfortunately not possible at the moment with custom widget and I should have mentioned it in the readme. The problem is a the custom widget cannot inherit the properties and callback functions of `PersistentTabView`. You will have to implement this yourself at this point.

I think it could be possible if you can save the context of each screen in a provider and then writing your own logic to pop screen using that context but that's all the help I can provide at this point unfortunately.

Alternatively, you can select a provided style. It will work perfectly fine with it.

```dart
navBarStyle: style1,
```

**Comment by felixferr** [comment]
Thanks i change to a normal nav barr and it works perfect thanks a lot for your work.
