### ISSUE TITLE
How can i use this package with PageRouteBuilder ?

### ISSUE THREAD

**Issue by felixferr** [BilalShahid13/PersistentBottomNavBar#25]
I would like use this animation : https://flutter.dev/docs/cookbook/animation/page-route-animation#interactive-example

How to hide the navigation bar and use the pageroutebuilder ?
Thx for reply

**Comment by BilalShahid13** [comment]
Do it like this: **Navigator.of(context, rootNavigator: true).push(_createRoute());**.

The `Navigator` functions that I have provided are just to make things simple and easy for users. You can use normal `Navigator` functions as well if you know what you doing.

**Comment by felixferr** [comment]
Thx
