### ISSUE TITLE
Show only icon

### ISSUE THREAD

**Issue by huiwen0212** [BilalShahid13/PersistentBottomNavBar#26]
Hi, may i know how can i just have a bottom navigation bar with just icon , i do not want to have title at the bottom. thanks

**Comment by BilalShahid13** [comment]
Set the property `title` of `PersistentBottomNavBarItem` as an **empty string i.e ""**

Alternatively, you can use style5 which do not show any text or nuemorphic style with no subtile.

**Comment by huiwen0212** [comment]
Hi, if I set the title to empty string i got this error

The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

I just want icon, not even the dot when it is selected

[image](https://user-images.githubusercontent.com/49686493/83158264-27217a00-a137-11ea-9587-08ab5aba03cf.png)

**Comment by BilalShahid13** [comment]
Try string with just a single space **" "**. This should work

**Comment by huiwen0212** [comment]
Hi, now it works, but the is there a params to make icon occupy the title space? because it does not look nice
![image](https://user-images.githubusercontent.com/49686493/83166910-27734280-a142-11ea-846b-04a3324c0b48.png)

**Comment by BilalShahid13** [comment]
Yes, you can control the size of the icon. Just declare the size of the icons of your navigation bar.

```dart
PersistentBottomNavBarItem(
        icon: Icon(Icons.search, size: 26.0),
);
```

Also, set the `bottomPadding` in the main `PersistentTabView` widget as *0.0* to get better results.

**Comment by BilalShahid13** [comment]
The latest version can now accept no `title` property. It will show no text with proper resizing when title is *null*.

**Comment by suchita-ounce** [comment]
I want to increase the size of icon. size parameter isn't working for me because I am using icon from asset. Below is the code I am using:

```
PersistentBottomNavBarItem(
        icon: new Image.asset("images/scan.png",width: 40, height: 40),
        title: ("Scan"),
      )


Here is the screenshot of how does it look:
![tabbar](https://user-images.githubusercontent.com/89699876/157275705-cc62a9d5-5a75-49a9-a812-310a56380699.png)
