### ISSUE TITLE
How to pushAndRemoveUntil a certain page without the nav bar?

### ISSUE THREAD

**Issue by nhlhelen** [BilalShahid13/PersistentBottomNavBar#260]
Hi I have this app which I would like to implement a logout feature. How do I pushAndRemoveUntil to RegisterPage() without the nav bar showing on the RegisterPage()? 

I'm using Flutter 2.5.3 & persistent_bottom_nav_bar: ^4.0.2, thanks a lot:)

`
Navigator.of(context).pushAndRemoveUntil(
    CupertinoPageRoute(
        builder: (BuildContext context) {
            return const RegisterPage();
        },
    ),
    (_) => false,
);
`

**Comment by PranayD1807** [comment]
This is the exact issue i am facing. If you found a solution, can you please post it?

**Comment by MianHaseeb** [comment]
**Hey, I found a solution to this problem.**

Navigator.of(context, rootNavigator: true).pushAndRemoveUntil(
      MaterialPageRoute(
        builder: (BuildContext context) {
          return SignInWidget();
        },
      ),
          (_) => false,
    );

**Comment by helen-hktaxiapp** [comment]
Thanks for the solution @MianHaseeb ! It works perfectly. 

I also found an alternate solution using the pushNewScreen() function and wrap the LoginPage() with WillPopScope() preventing it to go back. 

e.g.
pushNewScreen(context, screen: LoginPage(), withNavBar: false);

**Comment by nhlhelen** [comment]
Thanks for the solution @MianHaseeb ! It works perfectly.

I also found an alternate solution which I used the pushNewScreen() function and wrap the LoginPage() with WillPopScope(), preventing it to go back.

pushNewScreen(context, screen: const LoginPage(), withNavBar: false);
