### ISSUE TITLE
Make jumpToTab smoother

### ISSUE THREAD

**Issue by d-apps** [BilalShahid13/PersistentBottomNavBar#27]
Is it possible to add a smooth navigation when jumping to other tabs, I have a situation where my app has some tabs, when navigating from 0 to 1, it's ok, when 1 to 0 it's not very smooth, a little blunt.

Is it possivel to add some parameters like Duration, Curve, to make the animation when jumping to other tabs a little more smooth?

`persistentTabViewController.jumpToTab(tabNumber, duration:Duration(miliseconds: 300) , curve: Curves.easeOut);`

Thank you for making this amazing package.

**Comment by BilalShahid13** [comment]
The package doesn't provide any functionality at the moment like this. Maybe I will add it sometime in the future but I cannot give an ETA right now.

**Comment by BilalShahid13** [comment]
Feature added in the latest version i.e. **2.0.0+**. The animation can be controlled from the main `PersistentTabView` widget instead of the Navigator functions.

```dart
screenTransitionAnimation: ScreenTransitionAnimation( // Screen transition animation on change of selected tab.
        animateTabTransition: true,
        curve: Curves.ease,
        duration: Duration(milliseconds: 200),
      ),
```
