### ISSUE TITLE
How to hide persistent_bottom_nav_bar when the screen is not the main screens

### ISSUE THREAD

**Issue by wahyu-handayani** [BilalShahid13/PersistentBottomNavBar#270]
Hi, actually this question is duplicate from this: https://stackoverflow.com/q/70574114/13240914
I have asked this question in stackoverflow. I am currently using the newest version of persistent_bottom_nav_bar: ^4.0.2 to 3 screens (A,B,C screens) in the bottom tab navigator. In the first screen I have a button that navigate user to another screen (D screen). The problem is the bottom tab navigator (persistent_bottom_nav_bar) is still showing in D screen, while the main screens are AB,C. Is there a way to hide persistent_bottom_nav_bar when the screen is not one of three main screen ?

**Comment by Adimarogonas** [comment]
You've probably found the answer by now but you can use
use withNavBar:false in pushNewScreen()
