### ISSUE TITLE
How to pushAndRemoveUntil to a screen without showing NavBar

### ISSUE THREAD

**Issue by Moise-Nturubika** [BilalShahid13/PersistentBottomNavBar#279]
I hope you will help me to find a solution to this problem.
In my projet, my profil screen are in the tabs of persistentTabView.
On this screen is the logout button, but when I click on it to return to the login page, it returns to the login page with the tabBar visible.
I use Navigator.of(context).pushAndRemoveUntil function. How can i do to return to login page without showing the NavBar

**Comment by Adimarogonas** [comment]
`Navigator.of(context, rootNavigator: true).push() `
alternatively
` pushNewScreen(context, withNavBar: false, screen:YourScreen())`

**Comment by Moise-Nturubika** [comment]
@Adimarogonas thank you. The problem is resolved by the first proposition: Navigator.of(context, rootNavigator: true).pushAndRemoveUntil().
