### ISSUE TITLE
How to refresh screen

### ISSUE THREAD

**Issue by anup-geeky** [BilalShahid13/PersistentBottomNavBar#28]
I have two bottom navigation item, Home and Watchlist. In Home screen I am showing list of videos and in Watchlist shows list of videos marked as AddToWatchlist from Home screen. 
My problem is when I add video to Watchlist from Home screen, I want to refresh Watchlist to show updated list when I tap Watchlist icon. 
So my question is in which method/callback function should I write logic for this? No any function other than build() called in Watchlist.
Please give me a solution.
Thank you.

**Comment by BilalShahid13** [comment]
I would suggest using state management solutions like provider or bloc. When you update the list you can change the state and accordingly update the list on home screen. Some other ways could be either using global key or using a call back method. Define the list where you have declared the persistent navigation bar. Pass the list to home screen and update it using a callback method. But I will highly recommend using provider for this.
