### ISSUE TITLE
This package need to updated for Flutter 3.0.

### ISSUE THREAD

**Issue by md-siam** [BilalShahid13/PersistentBottomNavBar#290]
I am getting these types of warnings in FLutter 3.0. 
Please upgrade this package.
![Screen Shot 2022-05-28 at 11 44 48 AM](https://user-images.githubusercontent.com/21225918/170812006-ee6ea7ee-6299-4fb3-9c56-30e35c9840df.png)

**Comment by nbnD** [comment]
Did you solve this?

**Comment by md-siam** [comment]
No [nbnD](https://github.com/nbnD) , I am notifying an issue.

**Comment by alexaung** [comment]
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/persistent_bottom_nav_bar-4.0.2/lib/persistent-tab-view.widget.dart:368:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {

**Comment by alexaung** [comment]
Not so sure they still maintain this repo.

**Comment by awaluddinkasim** [comment]
yeah this package really needs to be updated, love this so much

**Comment by alexaung** [comment]
I used https://pub.dev/packages/persistent_bottom_nav_bar_v2. Jannis Berndt is forked from this repo and maintaining.

**Comment by md-siam** [comment]
[alexaung](https://github.com/alexaung)

Thanks for sharing. Moving to persistent_bottom_nav_bar_v2 🙂
