### ISSUE TITLE
PersistentBottomNavBarItem icon properties don't support for another widget 

### ISSUE THREAD

**Issue by khaitq7** [BilalShahid13/PersistentBottomNavBar#30]
Dear Bilal ,
The first , thank for your library .
It's great library .
But it will perfect if don't have two problem when implementation your library 

1. use another widget in PersistentBottomNavBarItem (Image.asset , ImageIcon , Container) ...
They will scale down and very small .
```
List<PersistentBottomNavBarItem> _navBarsItems() {
    return [
      PersistentBottomNavBarItem(
        icon: Image.asset('ic_home.png'),
        title: ("Home"),
        activeColor: Colors.deepOrangeAccent,
        inactiveColor: Colors.grey,
        isTranslucent: false,
      ),
      PersistentBottomNavBarItem(
        icon: Icon(CustomIcon.ic_giftcode),
        title: ("Giftcode"),
        activeColor: Colors.deepOrangeAccent,
        inactiveColor: Colors.grey,
        isTranslucent: false,
      ),
      PersistentBottomNavBarItem(
        icon: Icon(CustomIcon.ic_notice),
        title: ("Thông báo"),
        activeColor: Colors.deepOrangeAccent,
        inactiveColor: Colors.grey,
        isTranslucent: false,
      ),
      PersistentBottomNavBarItem(
        icon: Icon(CustomIcon.ic_category),
        title: ("Danh mục"),
        activeColor: Colors.deepOrangeAccent,
        inactiveColor: Colors.grey,
        isTranslucent: false,
      ),
    ];
  }
```

The result .
<img width="323" alt="Screen Shot 2020-06-04 at 4 16 11 PM" src="https://user-images.githubusercontent.com/11715209/83738694-d520ad00-a67e-11ea-8ca5-f97b97627cdb.png">

2. Don't support switch icon active and inactive from asset for your library . 
You know IconData only support Monochrome .

It will flexiable when use have exist .
I hope you fix that problem .
Again ,
Thank you so much .

**Comment by amrkhamis** [comment]
Tried Transform.scale and it worked like a charm, thanks .

**Comment by amrkhamis** [comment]
for some reason when using arabic text, even with the trasnform widget, the icon gets minimized to ridiculous small size 
![Screen Shot 2020-06-04 at 10 39 27 PM](https://user-images.githubusercontent.com/5472358/83802941-52b2e000-a6b4-11ea-88b0-07689279ef5b.png)

**Comment by khaitq7** [comment]
@BilalShahid13 : Thank for your support .

The second problem 
PersistentBottomNavBarItem : have not properties for use active icon & inactive icon from asset .
Only support color active and inactive .

**Comment by BilalShahid13** [comment]
@amrkhamis 
Is the arabic text part of the picture or a *title*?

**Comment by BilalShahid13** [comment]
@khaitq7 
Which type of properties do you want?

**Comment by amrkhamis** [comment]
@BilalShahid13 its part of the title, very weird of it affecting the picture, as soon as I make it english the picture would look normal

**Comment by ductranminh** [comment]
hi @amrkhamis, I used this lib for flutter web & I had a trouble with the Transform.scale: the icon is blurry on some mobile browser ( I use svg icons) (these icons work well in normal widget in the screen). They 're too small without Transform.scale. Is there any a way to do the custom icon widget completely? Like I want to have another widget beside the icons?
