### ISSUE TITLE
Keyboard does not work with TextField when use BottomNavBar

### ISSUE THREAD

**Issue by gapgag55** [BilalShahid13/PersistentBottomNavBar#32]
When I use PersistentBottomNavBar, after I focus on TextField, the TextField is not move up even using SingleScrollChildView

**Comment by BilalShahid13** [comment]
Try my answer on issue #19. You have already done the `SingleChildScrollView` part so you skip that.

**Comment by gapgag55** [comment]
@BilalShahid13 It is worked! However, BottomNavBar is sticky with the keyboard when it is up. How can avoid in this case?

**Comment by gapgag55** [comment]
Oh, I already solved it by 

```
renderBottomNavBar() {
    bool _isKeyboardOpen = MediaQuery.of(context).viewInsets.bottom > 0;
    if (_isKeyboardOpen) return SizedBox.shrink();

    return CustomBottomNavigationBar(
      items: _navBarsItems(),
      onItemSelected: (index) {
        setState(() {  _controller.index = index; });
      },
      selectedIndex: _controller.index,
    );
}
```

**Comment by amrkhamis** [comment]
@gapgag55 Please, may i have further explanation on renderBottomNavBar(), where did you put it, or how you used it ?

**Comment by Seema11** [comment]
@gapgag55 What If I am in the second screen, then your solution doesn't work. Can you please help me with that?
