### ISSUE TITLE
Screen not scroll when keyboard appears.

### ISSUE THREAD

**Issue by tanzeemhussain** [BilalShahid13/PersistentBottomNavBar#34]
i made a chat screen where at the end of screen i used text field when keyboard appears  then the screen not scroll . Even i  have used **SingleChildScrollView** and **ListView** both......

**Comment by BilalShahid13** [comment]
Please see #32. It should solve your problem but in an unorthodox way. I will release a new update soon with a fix and I will suggest you wait for it instead. It shouldn't take long as I'm almost at the end now.

**Comment by tanzeemhussain** [comment]
> Please see #32. It should solve your problem but in an unorthodox way. I will release a new update soon with a fix and I will suggest you wait for it instead. It shouldn't take long as I'm almost at the end now.

ok bro

**Comment by michael-attal** [comment]
Hello, when do you plan to release the update ?

**Comment by BilalShahid13** [comment]
@michael-attal I'll do my best to push this weekend. I want to push as much breaking changes in one go as possible to make the transition for users to new version easier. Lately I have been unusually busy resulting in the delay.

**Comment by michael-attal** [comment]
Ok, thank you for letting me know.

**Comment by tanzeemhussain** [comment]
@BilalShahid13 bhai kindly jaldi ker de........

**Comment by BilalShahid13** [comment]
Update is live. It got delayed due to underestimation on my part of the work required.
