### ISSUE TITLE
NavBar for only specific pages.

### ISSUE THREAD

**Issue by emran92** [BilalShahid13/PersistentBottomNavBar#35]
pushNewScreen() method has withNavBar property. I was wondering, can I use it on specific pages only. Like I have 3 pages on a screen. 
For page one, I want the NavBar and click on that first page, I go to second page then, there's no NavBar and when I click something on that second page and go to third page I want to see the NavBar. Is it possible?
Please any help or suggestions is appreciated.

**Comment by BilalShahid13** [comment]
It is not possible with the **Navigator** functions but can be done with a little hack. Set the navBar height to 0 when you navigate to second page turn it back to **56.0** (default height) when you reach the third page.

**Comment by emran92** [comment]
Thanks! Haven't thought about it.
