### ISSUE TITLE
How to change the bottom bar from any page

### ISSUE THREAD

**Issue by namayz18** [BilalShahid13/PersistentBottomNavBar#37]
I have 4 bottom bar item and 4 controller. One of them is product list page and when I press one of the list it goes to the product page. I am showing the bottom bar in that page. The product page that has add bag button and when I press the button I want show the  number of items added in the bag tab icon. currently when I press other tab it shows me update of the number in icon. How can I can update the number and show the changes in the same page. I am new on flutter please help me. I am using Globals to store the count

**Comment by BilalShahid13** [comment]
You can use Provider[https://pub.dev/packages/provider] (recommended) or a callback method to pass your count to the screen/widget where navigation bar is declared and then from there update the count going into the navigation bar.
