### ISSUE TITLE
Set a border at the top in a navbarStyle predefined

### ISSUE THREAD

**Issue by StefanYYC** [BilalShahid13/PersistentBottomNavBar#38]
Hello, 

First thanks for your awesome package! It works like a charm for me!
I was just wondering if it was possible to add a border to my bottomNavBar.

I'm using a style that you created (NavbarStyle.5) but I would like to add a border at the top of it to looks like the pic underneath 
![tempsnip](https://user-images.githubusercontent.com/32258096/87560483-c684d700-c6bb-11ea-8da0-6cde6a36fe39.png)

Is it possible to do so ? If yes could you help me archieve it?
Thanks again!

**Comment by BilalShahid13** [comment]
It is possible but only in version **2.0.0 and above**. I would do it like this using the property `decoration`:

```dart
decoration: NavBarDecoration(
          border: Border(
            top: BorderSide(height: 5.0, color: Colors.black),
          ),
),
```

**Comment by StefanYYC** [comment]
Awesome! I'm running the latest version anyway, I will try that tmr and if it works I will close the issue! Thx for the reply

**Comment by StefanYYC** [comment]
I'm facing an issue caused by borderRadius, here is what it says:
 `The following assertion was thrown during paint():
A borderRadius can only be given for uniform borders.
'package:flutter/src/painting/box_border.dart':
Failed assertion: line 523 pos 12: 'borderRadius == null'`
And below it's the code I'm using:
```dart
@override
  Widget build(BuildContext context) {
    return PersistentTabView(
        controller: _controller,
        screens: _buildScreens(),
        items: _navBarsItems(),
        // Redundant here but defined to demonstrate for other than custom style
        confineInSafeArea: true,
        backgroundColor: Colors.white,
        popAllScreensOnTapOfSelectedTab: true,
        handleAndroidBackButtonPress: true,
        decoration: NavBarDecoration(
          border: Border(
            top: BorderSide(width: 5.0, color: Colors.black),
          ),
        ),
        onItemSelected: (int) {
          setState(
              () {}); // This is required to update the nav bar if Android back button is pressed
        },
        itemCount: 5,
        navBarStyle:
            NavBarStyle.style5 // Choose the nav bar style with this property
        );
  }
```
I've noticed that if I add a bottom/left/right to the border with the **exact** same properties (same width and same color), the error doesn't show anymore.
The problem is that it makes my navbar looks super weird.

**Comment by BilalShahid13** [comment]
Update to version **2.0.5** :) Thanks for reporting!

**Comment by StefanYYC** [comment]
It works! Good job :)

**Comment by BilalShahid13** [comment]
```dart
onItemSelected: (int) {
          setState(
              () {}); // This is required to update the nav bar if Android back button is pressed
        },
```

This is not required in your case BTW as you are not using a custom style.
