### ISSUE TITLE
Margin still showing when keyboard shows

### ISSUE THREAD

**Issue by bassel** [BilalShahid13/PersistentBottomNavBar#39]
In a scrollable screen, when the keyboard shows the bottom nav is disappearing but the margin left for it is still present.  

Here's a screenshot that shows what's happening (PS: The page ends where the scroll effect is shown):

![Screenshot_20200715_221626](https://user-images.githubusercontent.com/23396171/87586610-6f95f680-c6e9-11ea-8ff1-24eef958912e.jpg)

**Comment by bassel** [comment]
Update: the margin disappears when `resizeToAvoidBottomInset` is set to true (which is the expected behavior).  

I'll close the issue, but I guess it would be a good note to add in the README. It's not very trivial that  `resizeToAvoidBottomInset` should be explicitly set when the value of `hideNavigationBarWhenKeyboardShows` is also set to true

**Comment by BilalShahid13** [comment]
Thank you for the suggestion. I have updated the readme and now there is a comment regarding this in the **Getting Started** code.
