### ISSUE TITLE
Frame drop on routing animation

### ISSUE THREAD

**Issue by furkansarihan** [BilalShahid13/PersistentBottomNavBar#40]
Hello there, I am experiencing frame drop on routing animation only between first and second page. After first push, animations are just fine.

Frame drop can only be noticable on low end devices (Samsung A5 2015) or poor emulators.

I am curious what is causing this. I think author have some toughts.

Current version: 1.5.5

**Comment by BilalShahid13** [comment]
Can you share a GIF here? I haven't experienced it as of yet.

**Comment by BilalShahid13** [comment]
Which android emulator are you using? I tested it on Nexus S (4" screen) and it didn't show signs of any stutter. It's really strange. 

Also, you can try updating to the latest version and push new screen like this using a different screen transition animation:

```dart
pushNewScreen(
        context,
        screen: MainScreen(),
        withNavBar: true, // OPTIONAL VALUE. True by default.
        pageTransitionAnimation: PageTransitionAnimation.slideRight
    );
```

**Comment by HenglyEver** [comment]
I have the same problem and I am now using `persistent_bottom_nav_bar: ^2.0.5` but the problem still persists.

**Comment by BilalShahid13** [comment]
@furkansarihan @HenglyEver does it occur while running the sample project and when using a different `pageTransitionAnimation` in the latest version?

```dart
pushNewScreen(
        context,
        screen: MainScreen(),
        withNavBar: true,
        pageTransitionAnimation: PageTransitionAnimation.slideRight // Change THIS
    );
```

**Comment by HenglyEver** [comment]
Well, the frame does drop on debug application regardless of page transition animation but on release application, it seems to be fine and works smoothly

**Comment by BilalShahid13** [comment]
@furkansarihan can you confirm what @HenglyEver said?
