### ISSUE TITLE
Increase area icon

### ISSUE THREAD

**Issue by felixferr** [BilalShahid13/PersistentBottomNavBar#42]
Hi, I Want to increase the area of each icons on my nav bar. My goal is to not missclick when i tap on the icon.

**Comment by BilalShahid13** [comment]
I don't completely understand what you mean. Do you mean increasing the tappable area to the surrounding white space as well?

You can try decreasing the horizontal padding if you are not using a custom widget as the icons should already spread in the space provided. But tappable area will be confined to the size of the icon.
