### ISSUE TITLE
Style 15 Icon

### ISSUE THREAD

**Issue by 3rsin3rgul** [BilalShahid13/PersistentBottomNavBar#43]
Hello,
I could not able to set icon for middle button. 
And can I use ImageIcon here?
![Screenshot 2020-07-26 at 20 47 57](https://user-images.githubusercontent.com/25375440/88486906-5ca0e300-cf81-11ea-8cc3-e29baf8b1a58.png)

**Comment by BilalShahid13** [comment]
Use `activeContentColor` to set the color of the icon within the middle item. And yes, you can use any widget as an icon.
