### ISSUE TITLE
A PersistentTabController was used after being disposed.

### ISSUE THREAD

**Issue by ayushnayyar** [BilalShahid13/PersistentBottomNavBar#44]
I am using a Future Builder to return the Main Bottom Navigation (Persistent Bottom Nav Bar) or the Signup Page. I get this error: A PersistentTabController was used after being disposed.

I also get this error when I go back from the MainBottomNav.

**Comment by BilalShahid13** [comment]
Yes, I noticed it too. I will release a fix as soon as I can. Thank you for reporting the bug!

**Comment by xanf-code** [comment]
PersistentTabController was used after being disposed still persists.

**Comment by ayushnayyar** [comment]
Just don't dispose it at all, and it goes away.

**Comment by juzimmer** [comment]
I'm having the same issue. I'm not calling dispose(). Any idea on when a fix will land ?

**Comment by BilalShahid13** [comment]
Fixed the issue. Check the latest version!

**Comment by Jaideep-C** [comment]
@BilalShahid13 Should we dispose of the PersistentTabController in the latest version?
