### ISSUE TITLE
Black screen keyboard open

### ISSUE THREAD

**Issue by felixferr** [BilalShahid13/PersistentBottomNavBar#46]
- I see a black screen when keyboard open.![image](https://user-images.githubusercontent.com/47897646/88921610-198b8c00-d26f-11ea-8a8d-b9875860e528.png)

**Comment by AbsoluteVirtueXI** [comment]
I think this is related to nested scaffold, but i am unable to get rid of this black screen while using PersistentBottomNavBar package. Maybe you can share some code it would help to reproduct the error

**Comment by BilalShahid13** [comment]
You are probably giving padding or something like this to the screen. In the example project, this black bar doesn't appear. You can take help from there.

**Comment by felixferr** [comment]
<img width="706" alt="Capture d’écran 2020-08-05 à 21 09 54" src="https://user-images.githubusercontent.com/47897646/89453770-03df0080-d760-11ea-8edc-81894e2d14eb.png">
This black screen produce when i press this TextField. I try with : resizeToAvoidBottomInset: false but already not work

**Comment by felixferr** [comment]
I set   resizeToAvoidBottomInset to false in the PersistentTabView and it works !!
