### ISSUE TITLE
Color transparent

### ISSUE THREAD

**Issue by felixferr** [BilalShahid13/PersistentBottomNavBar#48]
When i set colors transparent to the backgroundColor PersistentTabView, a background black color appear. How to fix that ? Thx
<img width="433" alt="Capture d’écran 2020-08-03 à 11 20 00" src="https://user-images.githubusercontent.com/47897646/89167692-02ed7980-d57c-11ea-9f4e-2f2f125ea6c6.png">

**Comment by BilalShahid13** [comment]
What color do you want to give? Or do you want the selected tab's screen behind your navigation bar? Also, please share the code here.

**Comment by felixferr** [comment]
<img width="291" alt="Capture d’écran 2020-08-05 à 20 33 47" src="https://user-images.githubusercontent.com/47897646/89450529-f83d0b00-d75a-11ea-9dd1-ad16771da6f3.png">
 i just want sent colors transparent

**Comment by BilalShahid13** [comment]
Try this:

‘’’dart
confineToSafeArea: false,
bottomScreenMargin: 0.0,
‘’’

**Comment by felixferr** [comment]
<img width="438" alt="Capture d’écran 2020-08-05 à 20 45 57" src="https://user-images.githubusercontent.com/47897646/89451543-abf2ca80-d75c-11ea-81f6-fdef06451504.png">
the problem with confineToSafeArea: false, the buttons are not in the area

**Comment by felixferr** [comment]
<img width="457" alt="Capture d’écran 2020-08-05 à 20 46 51" src="https://user-images.githubusercontent.com/47897646/89451645-cc228980-d75c-11ea-897d-01e83ccbc4e8.png">
and if i change confineToSafeArea to true this is the result

**Comment by BilalShahid13** [comment]
Okay now try this:

```dart
PersistentTabView(
      confineToSafeArea: true,
      backgroundColor: Colors.transparent,
);
```
Remove the **bottomScreenMargin** property.

Now in all your **PersistentBottomNavBarItem(s)** (If you want it to be transparent in all screens), set the **opacity**: 0.0:

```dart 
 PersistentBottomNavBarItem(
        opacity: 0.0,
      ),
```
