### ISSUE TITLE
Exception when using custom navBar on items is null even when passing itemCount

### ISSUE THREAD

**Issue by Yetispapa** [BilalShahid13/PersistentBottomNavBar#49]
Im' currently facing the issue that the following line is throwing an exception that `items is null`:

`assert(assertMidButtonStyles(navBarStyle, items.length),`

Even when I pass the following parameter:

`itemCount: items.length, // This is required in case of custom style! Pass the number of items for the nav bar.`

It seems there is a simple condition missing

**Comment by BilalShahid13** [comment]
Can you please share your code around **PersistentTabView**? Also are you using a custom style?

**Comment by Yetispapa** [comment]
This will fail:

```
PersistentTabView(
        controller: _controller,
        itemCount: items.length, // This is required in case of custom style! Pass the number of items for the nav bar.
        screens: _buildScreens(),
        confineInSafeArea: true,
        handleAndroidBackButtonPress: true,
        onItemSelected: (int) {
            setState(() {}); // This is required to update the nav bar if Android back button is pressed
        },
        customWidget: CustomNavBarWidget( // Your custom widget goes here
            items: _navBarsItems(),
            selectedIndex: _controller.index,
            onItemSelected: onItemSelected: (index) {
                setState(() {
                    _controller.index = index; // NOTE: THIS IS CRITICAL!! Don't miss it!
                });
            },
        ),
        navBarStyle: NavBarStyle.custom, // Choose the nav bar style with this property
        );
```

My fix was:

```
PersistentTabView(
          items: items, // <== my fix
        controller: _controller,
        itemCount: items.length, // <== this will be ignored | This is required in case of custom style! Pass the number of items for the nav bar.
        screens: _buildScreens(),
        confineInSafeArea: true,
        handleAndroidBackButtonPress: true,
        onItemSelected: (int) {
            setState(() {}); // This is required to update the nav bar if Android back button is pressed
        },
        customWidget: CustomNavBarWidget( // Your custom widget goes here
            items: _navBarsItems(),
            selectedIndex: _controller.index,
            onItemSelected: onItemSelected: (index) {
                setState(() {
                    _controller.index = index; // NOTE: THIS IS CRITICAL!! Don't miss it!
                });
            },
        ),
        navBarStyle: NavBarStyle.custom, // Choose the nav bar style with this property
        );
```

**Comment by BilalShahid13** [comment]
Yes, I think after the last update an assert is conflicting with the custom widget. Thanks for reporting it and I'll hopefully fix it in the upcoming update!

For now you can go on with the fix that you found. When using customWidget, the items don't matter as they wont be used so passing dummy items list will do here until the next update.

**Comment by BilalShahid13** [comment]
Also keep in mind that some features like `popAllScreensOnTapOfSelectedTab` will not work with custom widget. You will have to use the provided styles for that or implement it yourself in the custom widget.

**Comment by Yetispapa** [comment]
Good to know with `popAllScreensOnTapOfSelectedTab`

Thanks for your quick response and of course thanks for the great framework!

**Comment by Alwin-Lazar** [comment]
Same issue here. I can not use @Yetispapa solution in my case. Because I am using CustomBottomNavBarItem which is not same to items's datatype (PersistentBottomNavBarItem). So I expect a quick fix on this issue. And your are doing a amazing work @BilalShahid13 . We really appreciate that.

**Comment by PocketDaniel** [comment]
> Same issue here. I can not use @Yetispapa solution in my case. Because I am using CustomBottomNavBarItem which is not same to items's datatype (PersistentBottomNavBarItem). So I expect a quick fix on this issue. And your are doing a amazing work @BilalShahid13 . We really appreciate that.

Same here, but as a "temporary workaround" a.k.a. hack I am creating dummy list with _PersistentBottomNavBarItem_ and some random icon:
```
items: List<PersistentBottomNavBarItem>.generate(
    pages.length, // Same as itemCount
    (index) => PersistentBottomNavBarItem(icon: Icon(Icons.home)),
),
```

**Comment by BilalShahid13** [comment]
Fix will be released this weekend. Thank you for your patience!

**Comment by Alwin-Lazar** [comment]
@BilalShahid13 Bro the issue still there. do something.

**Comment by CnuFederer** [comment]
Hi, This issue is still there. Can u pls release latest update.

Thanks.

**Comment by BilalShahid13** [comment]
This issue has been fixed in latest update!
