### ISSUE TITLE
Custom Widget

### ISSUE THREAD

**Issue by lain-ke** [BilalShahid13/PersistentBottomNavBar#5]
Hello, I was wondering if you could add an option for custom widgets.
Thanks for this amazing plugin!

**Comment by BilalShahid13** [comment]
Yes I will be adding it soon. I have already defined a structure for it but I'm quite busy these days. There are many updates in pipeline that I will push once I get the time. Stay tuned!

Thank you.

**Comment by lain-ke** [comment]
Hello, I really need to implement this custom widget ASAP, any updates?

**Comment by BilalShahid13** [comment]
Tomorrow hopefully :)

**Comment by BilalShahid13** [comment]
I have added the custom widget functionality in the verison `1.3.0`. Check out the readme for more information.

**Comment by lain-ke** [comment]
Thanks a lot!!
