### ISSUE TITLE
Custom font, padding icon with title, remove animation

### ISSUE THREAD

**Issue by beheobong** [BilalShahid13/PersistentBottomNavBar#50]
- How to remove animation change tab, change font title, change padding top title with icon tab?

**Comment by BilalShahid13** [comment]
- Remove animation: 
```dart 
screenTransitionAnimation: ScreenTransitionAnimation(animateTabTransition: false),
```

- The navigation bar uses you default app font. If you want to change it then enclose `PersistentTabView` in something like `Theme` and declare your font over there. I may add the option to change font more easily in the future but for now this is the solution.

- You can do that by reducing bottom padding of the navigation bar and increasing bottom padding of the icon. The property where you declare the app icon is a widget so you can enclose your icon in the `Padding` widget.

**Comment by BilalShahid13** [comment]
`The navigation bar uses you default app font. If you want to change it then enclose PersistentTabView in something like Theme and declare your font over there. I may add the option to change font more easily in the future but for now this is the solution.`

This feature has been added in latest update!

**Comment by mjarpitanand** [comment]
I want to apply font family to this widget ```PersistentBottomNavBarItem``` . Can post an example.
