### ISSUE TITLE
_history.isNotEmpty is not true causes by wrong root route name

### ISSUE THREAD

**Issue by ductranit** [BilalShahid13/PersistentBottomNavBar#52]
After I upgrade to the latest version 2.0.5, the code to pop to the root navigation is broken:
```
Navigator.of(context).popUntil(ModalRoute.withName("/"));
```
I see this crash log:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Navigator(dirty, dependencies: [_EffectiveTickerMode, HeroControllerScope], state: NavigatorState#de143(tickers: tracking 0 tickers)):
Assertion failed: 
../…/widgets/navigator.dart:4081
_history.isNotEmpty
is not true

The relevant error-causing widget was
    PersistentTabView 
lib/…/home/home_widget.dart:310
When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
packages/flutter/src/widgets/navigator.dart 4081:21                           build
packages/flutter/src/widgets/framework.dart 4681:28                           build
packages/flutter/src/widgets/framework.dart 4564:15                           performRebuild
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Assertion failed: 
../…/widgets/navigator.dart:4081
_history.isNotEmpty
is not true

The relevant error-causing widget was
    PersistentTabView 
lib/…/home/home_widget.dart
```

Then I found this hardcode route name `/9f580fc5-c252-45d0-af25-9429992db112` in [this](https://github.com/BilalShahid13/PersistentBottomNavBar/blob/163102ddcf8c4e8b0430404def3e149e9d0a6231/lib/models/tab-view.widget.dart#L87) and [this](https://github.com/BilalShahid13/PersistentBottomNavBar/blob/4e2cd821c09e8761973a1e7017fcf8ee4bd2fcc4/lib/persistent-tab-view.widget.dart#L397) code, so I have to fix the issue by using 
```
Navigator.of(context).popUntil(ModalRoute.withName("/9f580fc5-c252-45d0-af25-9429992db112"));
```
But I think the route name  definitely should not be hardcode like that

**Comment by BilalShahid13** [comment]
Try with `popAllScreensOnTapOfSelectedTab = false`.

**Comment by ductranit** [comment]
I tried it before and got the same error

**Comment by BilalShahid13** [comment]
Can you try popping by using this: 

```dart
 Navigator.popUntil(
                    context,
                    ModalRoute.withName(
                        '/9f580fc5-c252-45d0-af25-9429992db112'));
```

**Comment by ductranit** [comment]
> Can you try popping by using this:
> 
> ```dart
>  Navigator.popUntil(
>                     context,
>                     ModalRoute.withName(
>                         '/9f580fc5-c252-45d0-af25-9429992db112'));
> ```

Yes, that's what I try. You can read **above comment**. It works, but I think the route name definitely should not be hardcode like that magic text. It's so confused. At least you should have a constant for it and update the document. Just my suggestion.

**Comment by BilalShahid13** [comment]
As I said, there was no other way to achieve this. I already tried the `Navigator.canPop()` function but that was unreliable. Route name must be defined before hand but I can understand your concern. I may give an option in the next update to declare your own route name instead of **/9f580fc5-c252-45d0-af25-9429992db112** and update the readme accordingly.

**Comment by ductranit** [comment]
@BilalShahid13 that's great, thank you!

**Comment by BilalShahid13** [comment]
`initialRoute` property added in latest update!
