### ISSUE TITLE
can't set textStyle for title in PersistentBottomNavBarItem

### ISSUE THREAD

**Issue by AliHoseinpoor** [BilalShahid13/PersistentBottomNavBar#53]

**Comment by BilalShahid13** [comment]
This feature will be added soon. Stay tuned!

**Comment by SachinTanpure** [comment]
Yes this is much needed feature we need textStyle for PersistentBottomNavBarItem. Please please update ASAP.

**Comment by yashwp** [comment]
@BilalShahid13 Does your team has any timeline to push this feature? It's much required now!

**Comment by SachinTanpure** [comment]
> This feature will be added soon. Stay tuned!

Sir, when dow get this update? Our project is getting on this feature

**Comment by BilalShahid13** [comment]
Added the feature in latest update!

**Comment by BilalShahid13** [comment]
> @BilalShahid13 Does your team has any timeline to push this feature? It's much required now!

There is no team. This in my personal project that I work on in my free time. Due to pandemic situation and lockdown, I couldn't spare enough time as my normal workload increased and efficiency decreased.
