### ISSUE TITLE
Example unclear

### ISSUE THREAD

**Issue by harshkumarkhatri** [BilalShahid13/PersistentBottomNavBar#54]
The example which you have given in the example section https://pub.dev/packages/persistent_bottom_nav_bar/example is unclear and does not show how a persistent app bar should be created. Please add some more examples each displaying about the styles you shown in your readme file.

**Comment by BilalShahid13** [comment]
Yes, it is unclear on the package's page. I'll update it soon hopefully.

**Comment by BilalShahid13** [comment]
Example section has been updated!
