### ISSUE TITLE
How to navigate from one bottom tab to another?

### ISSUE THREAD

**Issue by EngAddow** [BilalShahid13/PersistentBottomNavBar#58]
<img width="619" alt="Screen Shot 2020-08-23 at 9 16 30 PM" src="https://user-images.githubusercontent.com/35359329/90985779-d16a3b80-e586-11ea-9893-6c9b76421e52.png">

I want to navigate from settings tab to home tab as in that picture how?

**Comment by BilalShahid13** [comment]
Please see #45

**Comment by EngAddow** [comment]
Hi @BilalShahid13 I noticed some problems here: when I use images for the PersistentBottomNavBarItem icon the color of the image is not change according to the active and inactive item is there solution for this?

**Comment by BilalShahid13** [comment]
You'll have to use either icons or SVGs for it to change colour. Images cannot change their colour unfortunately.

**Comment by EngAddow** [comment]
> You'll have to use icons her. Images cannot change their colour unfortunately.

I have ben using another solution for the persistent bottom tabs but the only problem I had is when u want to jump from tab to tab I didnt get solution there, then I got jumpToIndex in ur solution which made me to try but I got problems that is very important for me :

**Comment by BilalShahid13** [comment]
The data in the each tab has nothing to do with navigation bar. It just shows a screens with tabs attached to it. Whatever logic you have in that screen must handle the persistence of the data. You can use provider or shared preferences for that purpose.

**Comment by EngAddow** [comment]
> The data in the each tab has nothing to do with the navigation bar. It just shows screens with tabs attached to it. Whatever logic you have in each screen must handle the persistence of the data. You can use provider or shared preferences for that purpose.

but this package catches each tab content @BilalShahid13

**Comment by BilalShahid13** [comment]
Yes, the state of each tab is persisted as long as the app is running. I guess I didn't understand your question. Can you share a GIF or a picture at least?

**Comment by EngAddow** [comment]
I will share with u soon thanks

**Comment by EngAddow** [comment]
> Yes, the state of each tab is persisted as long as the app is running. I guess I didn't understand your question. Can you share a GIF or a picture at least?
![image](https://user-images.githubusercontent.com/35359329/95676941-bd2bdd80-0bca-11eb-9169-e46613ae8b0c.png)

see this plz
