### ISSUE TITLE
Question about widget tree and hierarchy level

### ISSUE THREAD

**Issue by fernando-s97** [BilalShahid13/PersistentBottomNavBar#59]
Hi!

**Context**
My app is using 4 bottom tabs. One of them (tabItem3) has a BluetoothTabPage widget that will choose between ListAllDevicesPage and DeviceDataPage using a StreamBuilder.

The DeviceDataPage has some app bar actions that can push other pages, lets say DeviceSettingsPage and AnotherDeviceSettingsPage.

**Question**
My expectation when seeing the Widget Tree were:

- The first time I click on the tabItem3, the StreamBuilder of the BluetoothTabPage will show me the ListAllDevicesPage:
```
tabView
  - tabItem1
    - SomePage1
  - tabItem2
    - SomePage2
  - tabItem3
    - BluetoothTabPage
      - **ListAllDevicesPage**
  - tab4
    - SomePage4
```

- Once I select a device and connect to it, the StreamBuilder of the BluetoothTabPage will change, and show me the DeviceDataPage:
```
tabView
  - tabItem1
    - SomePage1
  - tabItem2
    - SomePage2
  - tabItem3
    - BluetoothTabPage
      - **DeviceDataPage**
  - tab4
    - SomePage4
```

- When I select one of the app bar actions it will push a new screen, lets say, the DeviceSettingsPage for example:
```
tabView
  - tabItem1
    - SomePage1
  - tabItem2
    - SomePage2
  - tabItem3
    - BluetoothTabPage
      - DeviceDataPage
        - **DeviceSettingsPage**
  - tab4
    - SomePage4
```

But here is the "problem". The above tree is what I expected, but what I have instead is:
```
tabView
  - tabItem1
    - SomePage1
  - tabItem2
    - SomePage2
  - tabItem3
    - BluetoothTabPage
      - DeviceDataPage
  - **DeviceSettingsPage**
  - tab4
    - SomePage4
```
The ListAllDevicesPages and the DeviceDataPage are chosen by the StreamBuilder, so there is no push involved. Fine. But once I'm in the DeviceDataPage and do a ```pushNewScreen(DeviceSettingsPage)```, the DeviceSettingsPage is added to the widget tree in the same level of the tabs.

Is this behavior correct? If so, how could I achieve the expected widget tree?
```
tabView
  - tabItem1
    - SomePage1
  - tabItem2
    - SomePage2
  - tabItem3
    - BluetoothTabPage
      - DeviceDataPage
        - DeviceSettingsPage
  - tab4
    - SomePage4
```

**Comment by BilalShahid13** [comment]
I see you tried very well to explain your problem but I don't think I understand it still. 

You said you app has 4 tabs but here I only see 3 with _ListAllDevices_ as a screen in the **BasePage** tab. Am I right?

```
tabView
  - tab1
  - tab2
  - BasePage
    - ListAllDevices
```

Are the new screens being added as new tabs here because they seem to be on the same level?

```
tabView
  - tab1
  - tab2
  - BasePage
    - DeviceData
  - DeviceSettings
  - AnotherDeviceSettings
```

If you can post some screenshots that'll be really helpful. Thanks.

**Comment by fernando-s97** [comment]
I've updated the question. Check if it got a little bit more clear. 

I guess the the screenshots would just pollute the question, since I have a lot of other widgets. This is just an abstraction. But if you think you really need them, I'll find a way to get it.

**Comment by BilalShahid13** [comment]
Sorry for late reply. 

The problem might be with `context` of the screen. The function `pushNewScreen()` is a normal **Navigator** function which has some additional options for ease of use. Make sure that correct context is passed to that screen and if that doesn't work then I guess sharing the screenshots might help me better understand the problem.
