### ISSUE TITLE
Pop to a new screen without the Nav Bar

### ISSUE THREAD

**Issue by SalmanFardeen** [BilalShahid13/PersistentBottomNavBar#61]
Hello there, I have a logout button and if I pop back to the login screen on it's on pressed, the bottom nav bar is still there. Can you please help me out with Pop back to a new page without having the bottom navigation bar? Thank You
![image](https://user-images.githubusercontent.com/68795988/91103743-0c0acb80-e68e-11ea-98a2-350abaeff9b6.png)

**Comment by Rayen-cherni** [comment]
do you fixed it ?
