### ISSUE TITLE
SVG image as icon active color not changed

### ISSUE THREAD

**Issue by aashishvyas** [BilalShahid13/PersistentBottomNavBar#62]
Used SVG images in icon for PersistentBottomNavBarItem but its color is not changed, working with normal flutter Icon

**Comment by BilalShahid13** [comment]
Yes, it will not work. You'll have to convert your SVG to icon file (ttf) and then import and use in the project. This [website](https://www.fluttericon.com) makes this process really simple.

**Comment by aashishvyas** [comment]
i have done that using custom style but have one issue with custom style. On back click from any  tab it navigate to first index screen but selected index still showing me as previous one.

**Comment by BilalShahid13** [comment]
You will have to call `setState` for it update.

**Comment by amanokerim** [comment]
@BilalShahid13 
I also have this problem:

> On back click from any tab it navigate to first index screen but selected index still showing me as previous one.

In docs said:
```
onItemSelected: (int) {
    setState(() {}); // This is required to update the nav bar if Android back button is pressed
},
```
But, there is no property onItemSelected.

My version: 4.0.2

Thank you ))
