### ISSUE TITLE
Showing a gray box over the NavBar in release build

### ISSUE THREAD

**Issue by SalmanFardeen** [BilalShahid13/PersistentBottomNavBar#63]
As-Salamu Alaikum brother. Thank you so much for this amazing package. Unfortunately, I am facing a little hiccup in the release build version. Whenever I click on the NavBar a gray box appears over the bar between the transitions when it works like a charm in debugged version.
Can you please help me out?
jazakallah khair.

![Animated GIF-downsized_large](https://user-images.githubusercontent.com/68795988/91248373-4cde0f80-e776-11ea-975e-22441dd5e09e.gif)

**Comment by BilalShahid13** [comment]
Waalaikumasalam. Does this occur only with this style or every style?

**Comment by SalmanFardeen** [comment]
> Waalaikumasalam. Does this occur only with this style or every style?

Alhamdulillah, I tried style6 and that one is working fine 😊.
