### ISSUE TITLE
pop once

### ISSUE THREAD

**Issue by ne-ray** [BilalShahid13/PersistentBottomNavBar#65]
Hi, thank you for package.
I do not know Dart very well, but I changed your package :)
I need custom functional:
ontap in button bar  pop once back of navigation.

I did enum type for `popAllScreensOnTapOfSelectedTab` all - equal current true, once - new function

see PR #66

**Comment by BilalShahid13** [comment]
Thank you for the idea. I will review your PR when possible.

**Comment by BilalShahid13** [comment]
PR approved and merged. Awesome work!
