### ISSUE TITLE
hideNavigationBarWhenKeyboardShows not working

### ISSUE THREAD

**Issue by mr-sharmaji** [BilalShahid13/PersistentBottomNavBar#67]
![Screenshot_20200827-074704 1](https://user-images.githubusercontent.com/33781108/91376037-cc80e280-e839-11ea-9bdf-e598369dc3de.jpg)
`
PersistentTabView(
            controller: _controller,
            screens: _buildScreens(),
            items: _navBarsItems(),
            confineInSafeArea: true,
            backgroundColor: Colors.white,
            handleAndroidBackButtonPress: true,
            resizeToAvoidBottomInset: true,
            stateManagement: true,
            hideNavigationBarWhenKeyboardShows: true,
            decoration: NavBarDecoration(
              boxShadow: [
                BoxShadow(
                  color: Colors.grey.withOpacity(0.3),
                  spreadRadius: 5,
                  blurRadius: 7,
                  offset: Offset(0, 3), // changes position of shadow
                ),
              ],
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(20.0),
                topRight: Radius.circular(20.0),
              ),
              colorBehindNavBar: Color(0xFFE0E0E0),
            ),
            popAllScreensOnTapOfSelectedTab: true,
            itemAnimationProperties: ItemAnimationProperties(
              duration: Duration(milliseconds: 200),
              curve: Curves.ease,
            ),
            screenTransitionAnimation: ScreenTransitionAnimation(
              animateTabTransition: true,
              curve: Curves.ease,
              duration: Duration(milliseconds: 100),
            ),
            navBarStyle: NavBarStyle.style15,
          ),
`

**Comment by anup-geeky** [comment]
Create one method to check is keyboard appear or not
  bool _keyboardIsVisible() {
    return !(MediaQuery.of(context).viewInsets.bottom == 0.0);
  }
And in build method call this method and set height of bottom navigation bar

if (_keyboardIsVisible()) {
      navBarHeight = 0;
      containerHeight = 0;
    }

**Comment by mr-sharmaji** [comment]
OKAY

**Comment by Nuke-101** [comment]
> 
> 
> Create one method to check is keyboard appear or not
> bool _keyboardIsVisible() {
> return !(MediaQuery.of(context).viewInsets.bottom == 0.0);
> }
> And in build method call this method and set height of bottom navigation bar
> 
please can you tell me where to place this condition as it can't be given in PersistentTabView
> if (_keyboardIsVisible()) {
> navBarHeight = 0;
> containerHeight = 0;
> }

**Comment by anup-geeky** [comment]
In build method where PersistentTabView is set.
@override
  Widget build(BuildContext context) {
    double navBarHeight = kBottomNavigationBarHeight, containerHeight = 60.0;
    if (_keyboardIsVisible()) {
      navBarHeight = 0;
      containerHeight = 0;
    }
return Scaffold(
    ...........
body: PersistentTabView(
        popAllScreensOnTapOfSelectedTab: true,
      ...................

**Comment by BilalShahid13** [comment]
> In build method where PersistentTabView is set.
> @override
> Widget build(BuildContext context) {
> double navBarHeight = kBottomNavigationBarHeight, containerHeight = 60.0;
> if (_keyboardIsVisible()) {
> navBarHeight = 0;
> containerHeight = 0;
> }
> return Scaffold(
> ...........
> body: PersistentTabView(
> popAllScreensOnTapOfSelectedTab: true,
> ...................

You can try this but this shouldn't technically be required. If `hideNavigationBarWhenKeyboardShows` is set to **true**, this exact method is applied i.e. `!(MediaQuery.of(context).viewInsets.bottom == 0.0);` by the navigation bar. But you can let me know if this works for you.

**Comment by umairali435** [comment]
remove resize to avoid bottom padding to true
