### ISSUE TITLE
use drawer so generate

### ISSUE THREAD

**Issue by jicasa03** [BilalShahid13/PersistentBottomNavBar#68]
In my project I want to end drawer and show accross all screen for that I have used Scafflod and set PersistentTabView to body.  push drawer

**Comment by BilalShahid13** [comment]
Does a problem occur when you attempt you achieve this?

**Comment by BilalShahid13** [comment]
Check latest [example](https://github.com/BilalShahid13/PersistentBottomNavBar/tree/master/example) project for demonstration.
