### ISSUE TITLE
can we "pop" to a specific screen in a tab's navigation stack ?

### ISSUE THREAD

**Issue by SogoGolf** [BilalShahid13/PersistentBottomNavBar#7]
Lets say that we have 4 x screens in a navigation stack on tab 1.

Then we navigate the the 4th (last) screen in that navigation stack.

Is there a way that we can "pop" back to (say) the 2nd screen ?

If not, can this feature be added ?

**Comment by SogoGolf** [comment]
this was my bad as i can see its working as expected with Flutter api's:

for anyone else wondering:

**pop to any screen in the nav graph for a given tab:** 
```
Navigator.of(context).popUntil((route) {
     return route.settings.name == "Screen2";
});
```
**pop back to first screen in the nav graph for a given tab:**
```Navigator.of(context).popUntil(ModalRoute.withName("/"));```

might be worth you updating the readme with a simple example as im sure others will benefit

**Comment by BilalShahid13** [comment]
A decent suggestion. Thank you 👍

**Comment by anup-geeky** [comment]
@SogoGolf  where you have put this code?

**Comment by lyf571321556** [comment]
> en2 of Home (Home-

do you solve it?
