### ISSUE TITLE
How to remove BottomNavBar on When user logout from the application?

### ISSUE THREAD

**Issue by DhavalRKansara** [BilalShahid13/PersistentBottomNavBar#70]
After successfully logging out from the application I am clearing the stack and navigate to the login page and the navbar is not removing from the login page too.

```
Navigator.of(context).pushAndRemoveUntil(
                  MaterialPageRoute(builder: (context) => LoginPage()),
                  (Route<dynamic> route) => false);
```

**Comment by SalmanFardeen** [comment]
Navigator.of(context, rootNavigator: true).pushAndRemoveUntil(
          MaterialPageRoute(
            builder: (BuildContext context) {
              return LoginScreen();
            },
          ),
          (_) => false,
        );

**Comment by digamber-negi-apt** [comment]
> Navigator.of(context, rootNavigator: true).pushAndRemoveUntil( MaterialPageRoute( builder: (BuildContext context) { return LoginScreen(); }, ), (_) => false, );

logging again will remove it bottom navigation from the stack.

**Comment by primeeeeaa** [comment]
when i try to logging again after using this \
Navigator.of(context, rootNavigator: true).pushAndRemoveUntil( MaterialPageRoute( builder: (BuildContext context) { return LoginScreen(); }, ), (_) => false, );
i am not going to anywhere but my bottom navigation bar is gone

**Comment by yuvisingh01** [comment]
Thanks for helping out, it has solved my problem(headache)...

**Comment by gpalve** [comment]
**rootNavigator: true** was the key here..Solved my problem. Thanks
