### ISSUE TITLE
How to pop certain tabs to the first screen when a user logout?

### ISSUE THREAD

**Issue by karmelcorn** [BilalShahid13/PersistentBottomNavBar#71]
I am using Provider for the user model, how can make certain tabs pop to their first screen when it receive changes from the Provider. 

I think I am supposed to use something like this

```
Navigator.of(context).pushAndRemoveUntil(
      CupertinoPageRoute(
      builder: (BuildContext context) {
          return FirstScreen();
      },
      ),
      (_) => false,
  );
```

but I am not sure where to put the code. 

Thank you.

**Comment by karmelcorn** [comment]
I figured it out. I just need to push the context of the tab that I want to pop into the User Provider Model. When logout is triggered, I trigger the call to pop for each tab. 

```
          Navigator.of(tabScreen1).popUntil((route) => route.isFirst);
```

**Comment by smofe** [comment]
@karmelcorn How did you get the context of _tabScreen1_ ? I think I have a simlar problem but I don't know how to access the context of a different tab/widget.

**Comment by karmelcorn** [comment]
When tabScreen1 is created, I stored the context of tabScreen1 into the usermodel.  So when the user logs out, I am able to retrieve and pop back to tabScreen1. 

Hope this helps.
