### ISSUE TITLE
How do I apply shadow to PersistentBottomNavBarItem

### ISSUE THREAD

**Issue by yashwp** [BilalShahid13/PersistentBottomNavBar#73]
I'm not able to find out, how can I apply shadow to each item. Is there any work-arounds?

**Comment by BilalShahid13** [comment]
You can apply shadow to the entire navigation bar but not to each item. I didn't feel a need for it so never thought of including this but you can add it yourself by using the custom widget. Keep in mind though that by using custom widget some features of the navigation bar like `popAllScreensOnTapOfSelectedTab` will not work.
