### ISSUE TITLE
initial route

### ISSUE THREAD

**Issue by umairali435** [BilalShahid13/PersistentBottomNavBar#75]
how to get initail route and beautiful custom bottom navigation bar

**Comment by BilalShahid13** [comment]
Ability to set your own initial route should be available in an upcoming update. By custom navigation bar, you mean your own style for the navigation bar? If yes, read the later part of the readme and if something is uncertain then let me know.

**Comment by umairali435** [comment]
yeah i read it but i have a problem of initial route other issues solved

**Comment by BilalShahid13** [comment]
`initialRoute` property has been added in the latest version!
