### ISSUE TITLE
Behavior problem with popAllScreensForTabSelectedTab

### ISSUE THREAD

**Issue by kleber-rr** [BilalShahid13/PersistentBottomNavBar#76]
First of all, I want to congratulate you for the work.

I noticed a behavior bug. During navigation between the tabs, if you press the same button repeatedly and quickly, it disassembles the batteries in the same previous route.

This happens only if you press it very fast (something that the user can do to play ...).

Here is a GIF of the problem.

I used the example downloaded from GIT.

If there is a solution, help us.

![hatsApp_Video_2020-09-12_at_17 38 35](https://user-images.githubusercontent.com/4059762/93005468-26162c00-f51f-11ea-9a58-282af614e96a.gif)

**Comment by BilalShahid13** [comment]
Thanks for reporting the bug!

**Comment by BilalShahid13** [comment]
Fixed in latest version!
