### ISSUE TITLE
Main icon not visible with style 15+16

### ISSUE THREAD

**Issue by forgetabout** [BilalShahid13/PersistentBottomNavBar#77]
Maybe it is me, have tried a million things, but the icons are not visible with styles 15 and 16. How to solve this? Any way to set the icon color here?

<img width="357" alt="image" src="https://user-images.githubusercontent.com/59344690/93009353-f827fa80-f5a5-11ea-9968-49b6dfb353a3.png">

**Comment by oscargc** [comment]
Try this:

PersistentBottomNavBarItem(
      icon: Icon(Icons.home),
      title: ("Home"),
      activeColor: Colors.blue,
      activeContentColor: Colors.white,
      inactiveColor: Colors.grey,
    ),

**Comment by jc-dekruijff** [comment]
Works like a charm, thanks.
