### ISSUE TITLE
Navbar and keyboard

### ISSUE THREAD

**Issue by fernando-s97** [BilalShahid13/PersistentBottomNavBar#79]
Hi!

Using the following settings, the navbar isn't being hidden when the keyboard appears

```dart
return Scaffold(
      body: PersistentTabView(
        controller: _controller,
        screens: _InitialWidgetState._pages
            .map((e) => SafeArea(child: e.value1))
            .toList(),
        items: _InitialWidgetState._pages
            .map((e) => PersistentBottomNavBarItem(
                  icon: e.value2,
                  title: e.value3,
                  inactiveColor: Colors.black,
                  titleFontSize: Theme.of(context).textTheme.bodyText2.fontSize,
                ))
            .toList(),
        popAllScreensOnTapOfSelectedTab: false,
        navBarHeight: 65,
        navBarStyle: NavBarStyle.style13,
        decoration: NavBarDecoration(
          borderRadius: BorderRadius.circular(15),
          boxShadow: const [BoxShadow()],
        ),
      ),
      
    );
```

**Comment by BilalShahid13** [comment]
Add the following properties and try again 

```dart
resizeToAvoidBottomInset: true,
hideNavigationBarWhenKeyboardShows: true,
```

**Comment by fernando-s97** [comment]
I've added and the problem still persists.

Doing a quick look into the source code, I've noticed that the property `hideNavigationBarWhenKeyboardShows` of the `PersistentTabScaffold` widget isn't being used anywhere. The problem might reside there...

**Comment by BilalShahid13** [comment]
Yes, the property is not being used because there is nothing to be done over there. The functionality is in `persistent-tab-view.widget.dart` and is working for me. I have seen other users complain about its reliability so I am looking into it. Can you try running the example project bundled with my package? There is a text field on the main page and again, I can confirm for me it is working. If it is working for you as well then try to replicate the same screen widget structure/hierarchy used in the example.

**Comment by fernando-s97** [comment]
Got it! I'll try this ASAP

**Comment by fernando-s97** [comment]
Hi. I've tested here with your embedded example.

In the custom widget page, the navbar doesn't get hidden. In the built-in style, it does get hidden.

I've copied the same style (just changing the items and screen) of the built-in style, but in my app, the navbar still appears above the keyboard

**Comment by BilalShahid13** [comment]
Can you share you code here?

**Comment by fernando-s97** [comment]
H! The only two codes I've used is this one, and your own, from the embedded example app.

> Hi!
> 
> Using the following settings, the navbar isn't being hidden when the keyboard appears
> 
> ```dart
> return Scaffold(
>       body: PersistentTabView(
>         controller: _controller,
>         screens: _InitialWidgetState._pages
>             .map((e) => SafeArea(child: e.value1))
>             .toList(),
>         items: _InitialWidgetState._pages
>             .map((e) => PersistentBottomNavBarItem(
>                   icon: e.value2,
>                   title: e.value3,
>                   inactiveColor: Colors.black,
>                   titleFontSize: Theme.of(context).textTheme.bodyText2.fontSize,
>                 ))
>             .toList(),
>         popAllScreensOnTapOfSelectedTab: false,
>         navBarHeight: 65,
>         navBarStyle: NavBarStyle.style13,
>         decoration: NavBarDecoration(
>           borderRadius: BorderRadius.circular(15),
>           boxShadow: const [BoxShadow()],
>         ),
>       ),
>       
>     );
> ```

**Comment by Zaid101** [comment]
Same here

**Comment by Edvardas889** [comment]
And here :(

**Comment by BilalShahid13** [comment]
Try setting `resizeToAvoidBottomInset` as **true**.

**Comment by BilalShahid13** [comment]
I have identified the problem and a fixed will be coming soon. But for now there is a temporary fix. Either try removing the Scaffold or set the navigation bar **height** as `MediaQuery.of(context).viewInsets.bottom > 0 ? 0.0 : kBottomNavigationBarHeight`.

```dart
navBarHeight: MediaQuery.of(context).viewInsets.bottom > 0 ? 0.0 : kBottomNavigationBarHeight,
```

**Comment by PhyoeKo** [comment]
I am also getting like that.
:'(

**Comment by EngAddow** [comment]
@BilalShahid13 this issue still exists in the latest v

**Comment by EngAddow** [comment]
and the above code is not working for me

**Comment by EngAddow** [comment]
for now I am solving using this code:

**Comment by EngAddow** [comment]
I need to use custom style because I need the title to have style like fontfamily, fontsize and so on but custom style has a lot of issues can you make the title of persistentItem widget instead of String?

**Comment by azazadev** [comment]
get some other issue in my app using  hideNavigationBar:
            MediaQuery.of(context).viewInsets.bottom > 0 ? true : false,

so another temporary fix work for me is to set resizeToAvoidBottomInset on  on Scaffold

      builder: (context, model, child) => Scaffold(
        resizeToAvoidBottomInset: false,

**Comment by BilalShahid13** [comment]
The issue should be fixed in the latest version _3.1.0_.

**Comment by fernando-s97** [comment]
Fixed in 3.1.0

**Comment by omarnaser1997** [comment]
hideNavigationBar: MediaQuery.of(context).viewInsets.bottom > 0 ? true : false,

**Comment by mtardal** [comment]
This issue persists in the latest version (3.1.0).

**Comment by jigarfumakiya** [comment]
Yes the problem it still there  in `persistent_bottom_nav_bar: ^4.0.2`
Showing black space when keyboard closes
Can we please re open this issue?

**Comment by Miya49-p0** [comment]
hi

> Showing black space when keyboard closes

I think the problem is that the height of the navigation bar is 0 until the keyboard closes (`MediaQuery.of (widget.context) .viewInsets.bottom == 0`).

```flutter
// persistent-tab-view.widget.dart

_navBarHeight = (widget.resizeToAvoidBottomInset &&
            MediaQuery.of(widget.context).viewInsets.bottom > 0 &&
            widget.hideNavigationBarWhenKeyboardShows)
        ? 0.0
        : widget.navBarHeight ?? kBottomNavigationBarHeight;
```

So I decided to manage it myself.

```
@override
Widget build(BuildContext context) {
  return PersistentTabView(
    context,
    controller: _controller,
    screens: buildScreens(),
    items: navBarsItems(),
    confineInSafeArea: true,
    backgroundColor: Theme.of(context)
        .bottomNavigationBarTheme
        .backgroundColor!, // Default is Colors.white.
    handleAndroidBackButtonPress: true, // Default is true.
    resizeToAvoidBottomInset: false,
    stateManagement: true, // Default is true.
    hideNavigationBarWhenKeyboardShows: false,
    navBarHeight: MediaQuery.of(context).viewInsets.bottom > 56
        ? 0.0
        : kBottomNavigationBarHeight, // is true.
    popAllScreensOnTapOfSelectedTab: true,
    popActionScreens: PopActionScreensType.all,
    itemAnimationProperties: const ItemAnimationProperties(
      duration: Duration(milliseconds: 200),
      curve: Curves.ease,
    ),
    screenTransitionAnimation: const ScreenTransitionAnimation(
      animateTabTransition: false,
      curve: Curves.ease,
      duration: Duration(milliseconds: 200),
    ),
    navBarStyle: NavBarStyle.simple, // Choose the
  );
}
```

- hideNavigationBarWhenKeyboardShows is false
- resizeToAvoidBottomInset is false
- Comparison target 56 is navigation bar default heigh

**Comment by Irfadg** [comment]
anyone know the solution??
