### ISSUE TITLE
Scroll to Top when DoubleTap on icon

### ISSUE THREAD

**Issue by zzterrozz** [BilalShahid13/PersistentBottomNavBar#80]
Hi, 

How can I Scroll to Top when DoubleTap on icon please ? 

I tried something like this but nothing I tried work.

`PersistentBottomNavBarItem(
                  icon: GestureDetector(
                          onDoubleTap: () {
                            PrimaryScrollController.of(context).animateTo(
                              0.0,
                              duration: Duration(milliseconds: 500),
                              curve: Curves.decelerate,
                            );
                          },
                          child: Icon(
                            Icons.whatshot,
                            color: Colors.black,
                            size: 33.0,
                          ),
                        ),
                  title: "Home",
                  activeColor: Colors.black54,
                  inactiveColor: Colors.grey,
                ),
`

But have this error : 

`The following NoSuchMethodError was thrown while handling a gesture:
The method 'animateTo' was called on null.
Receiver: null`

Could you please help?

Thank you

**Comment by BilalShahid13** [comment]
This is a custom functionality. It might be added in a future update but as of now, you can only achieve this by using a custom widget. See the bottom part of the Readme for more information on how to use custom widget and what are its limitations.

**Comment by zzterrozz** [comment]
Hi Bilal,

Thank you for your answer.
How woud you please do scroll to top using `onItemSelected` instead of `onDoubleTap` ?

**Comment by BilalShahid13** [comment]
Use the `ScrollController` attached to that screen to move to the top. To access that controller either declare it on the screen where the navigation bar exists and pass it to that screen or use state management solutions like provider or bloc.

**Comment by BilalShahid13** [comment]
This functionality is now possible by using the function `onSelectedTabPressWhenNoScreensPushed`. The function will be called only when you double tap the tab item and no screens are pushed on top of that tab's first screen. You can then pass that screen's scroll controller to this function using provider or some other technique and make it go to the top.
