### ISSUE TITLE
How can i navigate to page doesn't exist in my list of screens

### ISSUE THREAD

**Issue by Rayen-cherni** [BilalShahid13/PersistentBottomNavBar#81]
In my navigation screen i use this code: 
` Widget build(BuildContext context) { 
    int _currentIndex=ModalRoute.of(context).settings.arguments as int;
    PersistentTabController _controller;

    _controller = PersistentTabController(initialIndex: _currentIndex);

  return PersistentTabView(
      controller: _controller,
      screens: _buildScreens(),
      items: _navBarsItems(),
      confineInSafeArea: true,
      backgroundColor: Colors.white,
      handleAndroidBackButtonPress: true,
      resizeToAvoidBottomInset: true, // This needs to be true if you want to move up the screen when keyboard appears.
      stateManagement: true,
      hideNavigationBarWhenKeyboardShows: true, // Recommended to set 'resizeToAvoidBottomInset' as true while using this argument.
      decoration: NavBarDecoration(
        borderRadius: BorderRadius.circular(10.0),
        colorBehindNavBar: Colors.white,
      ),
      popAllScreensOnTapOfSelectedTab: true,
      itemAnimationProperties: ItemAnimationProperties( // Navigation Bar's items animation properties.
        duration: Duration(milliseconds: 200),
        curve: Curves.ease,
      ),
      screenTransitionAnimation: ScreenTransitionAnimation( // Screen transition animation on change of selected tab.
        animateTabTransition: true,
        curve: Curves.ease,
        duration: Duration(milliseconds: 200),
      ),
      navBarStyle: NavBarStyle.style1, // Choose the nav bar style with this property.
    );
}
}
List<Widget> _buildScreens() {
        return [
        SettingsScreen(),
        PollScreen(),
        ProfileScreen(),
        // UndefinedPollScreen(),
        ];
    }

    List<PersistentBottomNavBarItem> _navBarsItems() {
        return [
          PersistentBottomNavBarItem(
                icon: Icon(Icons.settings),
                title: ("Settings"),
                activeColor: CupertinoColors.activeBlue,
                inactiveColor: CupertinoColors.systemGrey,
            ),
            PersistentBottomNavBarItem(
                icon: Icon(Icons.poll),
                title: ("Poll"),
                activeColor: CupertinoColors.activeBlue,
                inactiveColor: CupertinoColors.systemGrey,
            ),
            PersistentBottomNavBarItem(
                icon: Icon(Icons.person),
                title: ("Profile"),
                activeColor: CupertinoColors.activeBlue,
                inactiveColor: CupertinoColors.systemGrey,
            ),
            
        ];
    }
`
In my main i use this code : 
`
Widget build(BuildContext context) {
  
    return MultiProvider(providers: [
      ChangeNotifierProvider.value(value: Auth()),
      ChangeNotifierProvider.value(value: User()),
    ],
    child: MaterialApp(
      debugShowCheckedModeBanner: false,
      title:"GOMYVOTE",
      theme:ThemeData(
        primaryColor:Colors.amber,
         scaffoldBackgroundColor: Colors.white,
        ),
    routes: {
       "/":(ctx) => SplashScreen(),
      "/login_screen":(ctx)=>LoginScreen(),
      "/welcome_screen":(ctx)=>WelcomeScreen(),
      "/poll_screen":(ctx)=>PollScreen(),
      "/undefined_poll_screen":(ctx)=>UndefinedPollScreen(),
      "/successful_poll_screen":(ctx)=>SuccessufulPollScreen(),
      "/profile_screen":(ctx)=>ProfileScreen(),
      "/change_name_screen":(ctx)=>ChangeNameScreen(),
      "/change_password_screen":(ctx)=>ChangePasswordScreen(),
      "/navigation_bar_screen":(ctx)=>NavigationBarScreen(),
      "/settings_screen":(ctx)=>SettingsScreen(),
      //  "/":(ctx)=>ProfileScreen(),

    },
    ),
    );  
  }
`
**i want to go to profile then in profile screen i have a feature "change password" (change password doesn't exist im my liste of screens).**
**but my operation is rejected : 
console :** 
I/flutter ( 5812): The following assertion was thrown while handling a gesture:
I/flutter ( 5812): Could not find a generator for route RouteSettings("/change_password_screen", null) in the
I/flutter ( 5812): _CustomTabViewState.
I/flutter ( 5812): Generators for routes are searched for in the following order:
I/flutter ( 5812):  1. For the "/" route, the "builder" property, if non-null, is used.
I/flutter ( 5812):  2. Otherwise, the "routes" table is used, if it has an entry for the route.
I/flutter ( 5812):  3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not
I/flutter ( 5812): handled by "builder" and "routes".
I/flutter ( 5812):  4. Finally if all else fails onUnknownRoute is called.
I/flutter ( 5812): Unfortunately, onUnknownRoute was not set.
I/flutter ( 5812): 
I/flutter ( 5812): When the exception was thrown, this was the stack:
I/flutter ( 5812): #0      _CustomTabViewState._onUnknownRoute.<anonymous closure> (package:persistent_bottom_nav_bar/models/tab-view.widget.dart:97:9)
I/flutter ( 5812): #1      _CustomTabViewState._onUnknownRoute (package:persistent_bottom_nav_bar/models/tab-view.widget.dart:109:6)
I/flutter ( 5812): #2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:3363:36)
I/flutter ( 5812): #3      NavigatorState.pushNamedAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3480:34)
I/flutter ( 5812): #4      _ProfileScreenState.build.<anonymous closure> (package:GOMYVOTE/presentation/profile/profile_screen.dart:127:49)
I/flutter ( 5812): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
I/flutter ( 5812): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
I/flutter ( 5812): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
I/flutter ( 5812): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
I/flutter ( 5812): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
I/flutter ( 5812): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
I/flutter ( 5812): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
I/flutter ( 5812): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
I/flutter ( 5812): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
I/flutter ( 5812): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
I/flutter ( 5812): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
I/flutter ( 5812): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
I/flutter ( 5812): #20     _invoke1 (dart:ui/hooks.dart:267:10)
I/flutter ( 5812): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
I/flutter ( 5812): (elided 3 frames from dart:async)
I/flutter ( 5812): 
I/flutter ( 5812): Handler: "onTap"
I/flutter ( 5812): Recognizer:
I/flutter ( 5812):   TapGestureRecognizer#80645

**Comment by zzterrozz** [comment]
```
onTap: () => pushNewScreen(
                              context,
                              screen: YourScreen(),
                              withNavBar: false, // OPTIONAL VALUE. True by default.
                              pageTransitionAnimation: PageTransitionAnimation.slideRight, // OPTIONAL
                            ),
```
