### ISSUE TITLE
How to open BottomSheet from bottom bar tab and above BottomNavBar

### ISSUE THREAD

**Issue by SachinTanpure** [BilalShahid13/PersistentBottomNavBar#82]
We have requirement where bottom bar tabs are pulled from server and need to show in app when app start. Bottom bar tabs can be more than 6 tabs. So I can make last Tab as Show More tab and when i clicked on it, bottom sheet open which has remaining tab. I can make bottom sheet, but how to open bottom sheet when bottom bar tab pressed as right now it is tied to one particular screen.
Below is example that i need to achieve

![Screenshot 2020-09-22 at 5 11 12 PM](https://user-images.githubusercontent.com/6615247/93877814-afcfb180-fcf6-11ea-9324-ba2d30d21c49.png)

**Comment by SachinTanpure** [comment]
Okay. I have manage to open bottom sheet from bottom bar tab by using **PersistentBottomNavBarItem**  **onPressed** property. Basically it override PersistentTabView  default tab switching behaviour for this particular item.
But new problem start showing, i have used showModalBottomSheet, but it is not opening above bottom bar and hide existing bottom bar. @BilalShahid13 How to open bottom sheet above bottom bar?

**Comment by BilalShahid13** [comment]
This solution "**Use showModalBottomSheet and set the property `useRootNavigator` as true**" should work. You must be missing something here. Please check the example project as I have demonstrated it there.

**Comment by zehaoj** [comment]
@SachinTanpure Hi could you paste the onpressed function to make it work? I've been stuck here for a while. Thanks!

**Comment by faizii023** [comment]
> Okay. I have manage to open bottom sheet from bottom bar tab by using **PersistentBottomNavBarItem** **onPressed** property. Basically it override PersistentTabView default tab switching behaviour for this particular item. But new problem start showing, i have used showModalBottomSheet, but it is not opening above bottom bar and hide existing bottom bar. @BilalShahid13 How to open bottom sheet above bottom bar? I have tried your [#21 (comment)](https://github.com/BilalShahid13/PersistentBottomNavBar/issues/21#issuecomment-630062622) solution but it is not working.

Can You provide the code i also want to implement it

**Comment by MohammadAliK** [comment]
@SachinTanpure or anyone find solution regarding this issue?

**Comment by SotoArmando** [comment]
> This solution "**Use showModalBottomSheet and set the property `useRootNavigator` as true**" should work. You must be missing something here. Please check the example project as I have demonstrated it there.

Where is it?

**Comment by SachinTanpure** [comment]
Hello @SotoArmando @MohammadAliK @faizii023 
So I managed to show using showGeneralDialog with Container and bottom margin. 
I have added ShowMore PersistentBottomNavBarItem as the last item on bottom bar and onclick of it I am opening showGeneralDialog which has a bottom margin also transition effect to open from bottom of screen.

```
showGeneralDialog(
        barrierLabel: AppLocalizations.of(context).translate(LanguageConstant.more),
        barrierDismissible: true,
        barrierColor: Colors.grey.withOpacity(0.1),
        transitionDuration: Duration(milliseconds: 100),
        context: context,
        pageBuilder: (dialogContext, anim1, anim2) {
          return Align(
            alignment: Alignment.bottomCenter,
            child: Container(
              **margin: EdgeInsets.only(bottom: CommonConstants.BOTTOM_BAR_HEIGHT, top: MediaQuery.of(context).size.height/2, left: 0, right: 0),**
              decoration: BoxDecoration(
                  color: Theme.of(context).colorScheme.surface,
                  border: Border.all(width: 0.5,color: ColorConstants.blackShade3),
              ),
              child: GridView.builder(
                      padding: EdgeInsets.zero,
                      physics: NeverScrollableScrollPhysics(),
                      shrinkWrap: true,
                      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                        crossAxisCount: 5,
                        crossAxisSpacing: 5,
                        mainAxisSpacing: 5,
                      ),
                      itemCount: _bottomBarShowMoreTabs!.length,
                      itemBuilder: (dialogContext, index) {
                        return Material(
                          color: Theme.of(context).colorScheme.surface,
                          child: InkWell(
                            onTap: () {
                              Navigator.of(dialogContext).pop();
                              _pushNewScreenInCurrentScreen(
                                  _bottomBarShowMoreTabs![index].type,
                                  _bottomBarShowMoreTabs![index].title,
                                  );
                            },
                            child: Container(
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  CommonUtils.getBottomBarTabIconFromType(
                                      _bottomBarShowMoreTabs![index].type,
                                      context: context,
                                      badge: unReadNotificationCount),
                                  Text(
                                    _bottomBarShowMoreTabs![index].title!,
                                    textAlign: TextAlign.center,
                                    style: Theme.of(context)
                                        .textTheme
                                        .bodyText2!
                                        .copyWith(color: Colors.grey),
                                  )
                                ],
                              ),
                            ),
                          ),
                        );
                      },
                    ),
            ),
          );
        },
        transitionBuilder: (dialogContext, anim1, anim2, child) {
          return SlideTransition(
            position: Tween(begin: Offset(0, 1), end: Offset(0, 0)).animate(anim1),
            child: child,
          );
        },
      );
```
