### ISSUE TITLE
Show Drawer above bottomNavBar

### ISSUE THREAD

**Issue by mopilo** [BilalShahid13/PersistentBottomNavBar#83]
I intend to show either drawer or end-drawer above the nav bar, how do I achieve this?

**Comment by BilalShahid13** [comment]
```dart
Scaffold(
drawer: Drawer(),
body: PersistentTabView(),
);
```

**Comment by mopilo** [comment]
<img width="419" alt="Screenshot 2020-10-01 at 12 02 13 PM" src="https://user-images.githubusercontent.com/7842458/94801450-f64f9b00-03dd-11eb-9a95-efe9e47f5b10.png">


Tried that and it doesn't go above it. see Image

**Comment by BilalShahid13** [comment]
Please check the latest example project [here](https://github.com/BilalShahid13/PersistentBottomNavBar/tree/master/example). As demonstrated, the drawer has be on top of the navigation bar widget tree.

**Comment by mlph-cestremos** [comment]
@BilalShahid13 can you reopen this and give concrete resolution? I just follow this code but the drawer still does not overlap the nav bar: 
```
Scaffold(
   drawer: Drawer(),
   body: PersistentTabView(),
);
```
