### ISSUE TITLE
type 'Future<bool>' is not a subtype of type '() => Future<bool>' 

### ISSUE THREAD

**Issue by mr-sharmaji** [BilalShahid13/PersistentBottomNavBar#84]
Error when Trying to edit onWillPop **type 'Future<bool>' is not a subtype of type '() => Future<bool>'** 
` Future<bool> _onWillPop(index) async => await Future.value(true);`

` PersistentTabView(
      controller: _controller,
      screens: _buildScreens(),
      items: _navBarsItems(),
      onWillPop: _onWillPop(_controller.index),
      confineInSafeArea: true,
      backgroundColor: Colors.white,
      handleAndroidBackButtonPress: true,
      resizeToAvoidBottomInset: true,
      stateManagement: true,
      hideNavigationBarWhenKeyboardShows: true,
      popAllScreensOnTapOfSelectedTab: true,
      itemAnimationProperties: ItemAnimationProperties(
        duration: Duration(milliseconds: 200),
        curve: Curves.ease,
      ),
      decoration: NavBarDecoration(
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.3),
            spreadRadius: 5,
            blurRadius: 7,
            offset: Offset(0, 3), // changes position of shadow
          ),
        ],
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(20.0),
          topRight: Radius.circular(20.0),
        ),
        colorBehindNavBar: Color(0xFFE0E0E0),
      ),
      screenTransitionAnimation: ScreenTransitionAnimation(
        animateTabTransition: true,
        curve: Curves.ease,
        duration: Duration(milliseconds: 100),
      ),
      navBarStyle: NavBarStyle.style15,
    );`

**Comment by BilalShahid13** [comment]
Yes, it is a bug. Thanks for reporting it!

**Comment by BilalShahid13** [comment]
Fixed in latest version!
