### ISSUE TITLE
Swiping to change page

### ISSUE THREAD

**Issue by simeon9696** [BilalShahid13/PersistentBottomNavBar#87]
Hello, are there any built in methods that handle swiping to change the route? Or is this something one might have to handle with GestureDetector? 

If so can you please advise on that?

**Comment by BilalShahid13** [comment]
You will have to handle that yourself. I looked into this very feature sometime ago but stopped short of implementing it due to some issues. But I think it should be very easy for you to implement.

**Comment by mortenfriis** [comment]
My solution was to wrap the PersistentTabView with a GestureDetector and set the onHorizontalDragEnd property as follows:
`onHorizontalDragEnd: (DragEndDetails details) {
          if (details.primaryVelocity < 0 &&
              _controller.index != _navBarsItems().length - 1) {
            print(details.primaryVelocity);
            _controller.index++;
          } else if (details.primaryVelocity > 0 && _controller.index != 0) {
            print(details.primaryVelocity);
            _controller.index--;
          }
        }`
