### ISSUE TITLE
Is there any option to set for the tab I don't want to keep its state?

### ISSUE THREAD

**Issue by EngAddow** [BilalShahid13/PersistentBottomNavBar#89]
I have 5 persistent tabs 1 of them is favorite tab when I click on it and user is loged in it shows the favorites but then I go to another tab and logedout and come back to the favorite tab and favorites are still there how to solve this?

**Comment by BilalShahid13** [comment]
Individually, there is no option. You can either turn state management off or on. But you can achieve this yourself. Make a global key and pass on to that favourites screen. Then when logging out, use that key to refresh its state.

**Comment by EngAddow** [comment]
> Individually, there is no option. You can either turn state management off or on. But you can achieve this yourself. Make a global key and pass on to that favorites screen. Then when logging out, use that key to refresh its state.

thank you bro @BilalShahid13  **_do u mean I create navigator state key globally and pass to favorites if so how to refresh by using that key can u give a hint_**  and **_as I can see there is an option to turn off all state management while bottom nav is persistent can u give a hint for that too_**.

**Comment by BilalShahid13** [comment]
Yes, something like that. I tried it that a while ago but don't remember how I did it now. 

A better solution would be to use state management solution like provider or bloc in my opinion. Reset the state to initial when you logout while purging all the data in that screen.

**Comment by EngAddow** [comment]
> Yes, something like that. I tried it that a while ago but don't remember how I did it now.
> 
> A better solution would be to use state management solution like provider or bloc in my opinion. Reset the state to initial when you logout while purging all the data in that screen.

ok

**Comment by pishguy** [comment]
> Should you share you solution here?
> I am looking to refresh each state individually :)

and me too

@Add00w  please share your solution, thanks in advance

**Comment by pishguy** [comment]
@andreferreiravntrs 

could you resolve this problem?

**Comment by BilalAsif25** [comment]
Any solution for this really stuck on this its been a week , please share code snippet @Add00w @BilalShahid13 Thank you
