### ISSUE TITLE
can i programatically hide the nav bar from any view ? 

### ISSUE THREAD

**Issue by SogoGolf** [BilalShahid13/PersistentBottomNavBar#90]
Is there a way that we can show and hide the bottom nav bar "on demand", for example if a user taps on a button on any given screen ?

**Comment by BilalShahid13** [comment]
Yes, there is an argument in `PersistentTabView` named **hideNavigationBar**. When set as true/false, the navigation bar will disappear/appear with an animation.

**Comment by SogoGolf** [comment]
right but if i am currently on a child view somewhere in the stack, how can i hide the tab bar then ? to be specific - when the user lands on this child view - the tab bar IS showing. then, the user (say) taps a button -> which then HIDES the tab bar.

**Comment by EngAddow** [comment]
> right but if i am currently on a child view somewhere in the stack, how can i hide the tab bar then ? to be specific - when the user lands on this child view - the tab bar IS showing. then, the user (say) taps a button -> which then HIDES the tab bar.

make method callback to the parent page and handle it there.

**Comment by DhavalRKansara** [comment]
> right but if i am currently on a child view somewhere in the stack, how can i hide the tab bar then ? to be specific - when the user lands on this child view - the tab bar IS showing. then, the user (say) taps a button -> which then HIDES the tab bar.

Did you found any solution or workaround for this issue?

**Comment by BilalShahid13** [comment]
This scenario is demonstrated in the example project.
