### ISSUE TITLE
Support flutter navigation 2.0

### ISSUE THREAD

**Issue by Ted-Zhang** [BilalShahid13/PersistentBottomNavBar#91]
Just a question: By reading the navigator functions in Readme, I am not sure how the pushNewScreen/pushNewScreenWithRouteSettings will work with flutter navigation 2.0 in declarative way? and do we have plan to support it? Thanks.

**Comment by BilalShahid13** [comment]
Yes, I do plan to support it and will issue an update when it is ready.
