### ISSUE TITLE
Doubt about Android Back Button + onWillPop

### ISSUE THREAD

**Issue by fernando-s97** [BilalShahid13/PersistentBottomNavBar#93]
Hi!

I'm not sure if I understood how to properly use onWillPop.

Currently, I'm showing a dialog onWillPop, asking if the user really wanna leave.

My expected behavior: Users navigate through tabs and can use the back button to go back, popping the screens in the stack. If the stack only contains the initial screen, then onWillPop will be called, and my dialog will be shown.

Current behavior: No matter where in the stack I am, if I hit the back button, my dialog will show, which blocks my navigation with the back button. This way is like if the back button only purpose were to show the dialog at any point in time.

Is the current behavior the correct one? If so, how can I know if there is no screen in the stack, so I can show the dialog only in this case?

**Comment by BilalShahid13** [comment]
Have you wrapped `PersistentTabView` in a ``Scaffold`. If yes, try unwrapping it and give it another try. Also, I have updated the example project to demonstrate this. Let me know if it doesn't work for you over there as well.

**Comment by BilalShahid13** [comment]
Yes I can confirm it is not working correctly. Thanks for reporting it and I will hopefully fix it in an update. Time is an issue for me these days.

**Comment by fernando-s97** [comment]
Fixed in 3.0.0

**Comment by sloosh** [comment]
glad you fixed it, I just got that issue! Updating to 3.1.0 seems good, thanks !
