### ISSUE TITLE
Support for inactive icon when tab is not selected

### ISSUE THREAD

**Issue by Btrc4t** [BilalShahid13/PersistentBottomNavBar#97]
I noticed that there isn't support for an inactive icon for when a tab is inactive and I think it would be useful since there are versions of Icons for example in the "material" library which are basically the same icon but they have two versions, such as:

- Icons.assessment
- Icons.assessment_outlined

and this is the same for CupertinoIcons (although naming conventions are different):

- CupertinoIcons.arrow_up_doc_fill
- CupertinoIcons.arrow_up_doc

This is the only thing that I really missed from the library, otherwise I can say I'm really happy with the package

**Comment by EngAddow** [comment]
simple you can use boolean   isActive? Icons.active:icons.inActive

**Comment by BilalShahid13** [comment]
That's a good feature to request. As @EngAddow said, you can try the workaround for now.

**Comment by azazadev** [comment]
can we have this feature in next version ? 

otherwise how we can find the current selected Index to build bool isActive ? , I'm using basic PersistentTabView with predifine NavBarStyle.style1 and List of PersistentBottomNavBarItem, an sample can be appreciated

  List<PersistentBottomNavBarItem> _navBarsItems(bool isActive) {  // how we can build this bool ?
    return [
      PersistentBottomNavBarItem(
        icon: isActive ? Icon(CupertinoIcons.house_fill) : Icon(
            CupertinoIcons.house),
        iconSize: 25,
        activeColor: CupertinoColors.activeBlue,
        inactiveColor: CupertinoColors.systemBackground,
      ),
      ...
      ...

**Comment by BilalShahid13** [comment]
@azazadev implementation is complete and will release soon hopefully.

**Comment by azazadev** [comment]
> @azazadev implementation is complete and will release soon hopefully.

@BilalShahid13 Any news about next release ? :)

**Comment by BilalShahid13** [comment]
I'll do my best to release this weekend :)

**Comment by azazadev** [comment]
> I'll do my best to release this weekend :)

Thanks !

**Comment by azazadev** [comment]
> I'll do my best to release this weekend :)

Hi @BilalShahid13 any plans for next release ?

**Comment by azazadev** [comment]
> I'll do my best to release this weekend :)

Hi @BilalShahid13 any plans for next release ?

**Comment by sumitbhanushali** [comment]
waiting for this feature!

**Comment by BilalShahid13** [comment]
This feature is released starting version 3.2.0.
