### ISSUE TITLE
Page is not refreshing 

### ISSUE THREAD

**Issue by aTeamSolace** [BilalShahid13/PersistentBottomNavBar#98]
I've added 5 different tabs and each tab contains API call. When I reach that page the first time then it will call API perfectly but when ill reach that page a second time then this method cant working ??

and when I use the default bottom nav bar then it working fine

**Comment by EngAddow** [comment]
try to set 
```
stateManagement 
```
property to 
```
true
```

**Comment by NailTasgetiren** [comment]
How can I set false for just one tap? @EngAddow

**Comment by EngAddow** [comment]
> How can I set false for just one tap? @EngAddow

sorry no idea
