### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by EngAddow** [BilalShahid13/PersistentBottomNavBar#99]
I need to use custom style because I need the title to have style like fontfamily, fontsize and so on but custom style has a lot of issues can you make the title of persistentItem widget instead of String so we can use the predefined styles?

**Comment by BilalShahid13** [comment]
There is a field in `PersistentBottomNavBarItem` called **titleStyle**. You can input your custom text style using that.

**Comment by EngAddow** [comment]
yes I did thanks
